import React, { createContext, useContext, useState, useEffect } from "react";

// Supported Languages Definition
export type LanguageCode = "en" | "es" | "vi" | "hi" | "zh" | "fr" | "kn" | "ta" | "te" | "mr" | "ja";

export interface LanguageOption {
  code: LanguageCode;
  name: string;
  flag: string;
}

export const LANGUAGES: LanguageOption[] = [
  { code: "en", name: "English", flag: "🇺🇸" },
  { code: "es", name: "Español", flag: "🇪🇸" },
  { code: "vi", name: "Tiếng Việt", flag: "🇻🇳" },
  { code: "hi", name: "हिन्दी", flag: "🇮🇳" },
  { code: "kn", name: "ಕನ್ನಡ (Kannada)", flag: "🇮🇳" },
  { code: "ta", name: "தமிழ் (Tamil)", flag: "🇮🇳" },
  { code: "te", name: "తెలుగు (Telugu)", flag: "🇮🇳" },
  { code: "mr", name: "मराठी (Marathi)", flag: "🇮🇳" },
  { code: "ja", name: "日本語 (Japanese)", flag: "🇯🇵" },
  { code: "zh", name: "中文", flag: "🇨🇳" },
  { code: "fr", name: "Français", flag: "🇫🇷" }
];

export const TRANSLATIONS: Record<LanguageCode, Record<string, string>> = {
en: {
    "Community Hero": "Community Hero",
    "Civic Action Platform": "Civic Action Platform",
    "Civic Map & Grid": "Civic Map & Grid",
    "Impact Analytics": "Impact Analytics",
    "Sign In / Join": "Sign In / Join",
    "Notice a civic issue?": "Notice a civic issue?",
    "File Quick Civic Report": "File Quick Civic Report",
    "Active Civic Reports": "Active Civic Reports",
    "Austin Civic Grid": "Austin Civic Grid",
    "Click anywhere on the map to log a new issue": "Click anywhere on the map to log a new issue",
    "Map Legend": "Map Legend",
    "Reported": "Reported",
    "Verified": "Verified",
    "In Progress": "In Progress",
    "Resolved": "Resolved",
    "Pothole": "Pothole",
    "Water Leak": "Water Leak",
    "Broken Streetlight": "Broken Streetlight",
    "Trash & Dumping": "Trash & Dumping",
    "Graffiti": "Graffiti",
    "Other": "Other",
    "Low": "Low",
    "Medium": "Medium",
    "High": "High",
    "Critical": "Critical",
    "Sign Out": "Sign Out",
    "Verifications": "Verifications",
    "Verify Issue": "Verify Issue",
    "Update Status": "Update Status",
    "Speak": "Speak",
    "Listen": "Listen",
    "Translate": "Translate",
    "Photo Attachment": "Photo Attachment",
    "Voice note attached": "Voice note attached",
    "No issues matching filters": "No issues matching filters",
    "Try changing your filters or report a new issue directly on the map.": "Try changing your filters or report a new issue directly on the map.",
    "Click directly on the interactive grid map on the right to pinpoint a precise location, or file an instant report.": "Click directly on the interactive grid map on the right to pinpoint a precise location, or file an instant report.",
    "Austin Civic Center": "Austin Civic Center",
    "Recommended Action": "Recommended Action",
    "Points": "Points",
    "Your Level": "Your Level",
    "Active Reports": "Active Reports",
    "Leaderboard": "Leaderboard",
    "Badges Earned": "Badges Earned",
    "Earn rewards by reporting and verifying neighborhood issues. Become a localized community hero!": "Earn rewards by reporting and verifying neighborhood issues. Become a localized community hero!",
    "Sign in to start earning points, tracking achievements, and verifying issues!": "Sign in to start earning points, tracking achievements, and verifying issues!",
    "Description": "Description",
    "Location Name": "Location Name",
    "Civic Impact Analytics": "Civic Impact Analytics",
    "Report New Civic Issue": "Report New Civic Issue",
    "Title": "Title",
    "Category": "Category",
    "Urgency": "Urgency",
    "Submit Report": "Submit Report",
    "Your Name": "Your Name",
    "Email Address": "Email Address",
    "Password": "Password",
    "Create Hero Account": "Create Hero Account",
    "Sign In": "Sign In",
    "All Statuses": "All Statuses",
    "Stop Reading": "Stop Reading",
    "Translating...": "Translating...",
    "Show Original": "Show Original",
    "Verified By You": "Verified By You",
    "Verifying...": "Verifying...",
    "Cancel": "Cancel",
    "Live Google Maps": "Live Google Maps",
    "Custom Interactive Grid": "Custom Interactive Grid",
    "File a Civic Report": "File a Civic Report",
    "Coordinate": "Coordinate"
  },
  es: {
      "Community Hero": "Héroe Comunitario",
      "Civic Action Platform": "Plataforma de Acción Cívica",
      "Civic Map & Grid": "Mapa y Cuadrícula Cívica",
      "Impact Analytics": "Análisis de Impacto",
      "Sign In / Join": "Iniciar Sesión / Unirse",
      "Notice a civic issue?": "¿Notas un problema cívico?",
      "File Quick Civic Report": "Presentar Reporte Cívico Rápido",
      "Active Civic Reports": "Reportes Cívicos Activos",
      "Austin Civic Grid": "Cuadrícula Cívica de Austin",
      "Click anywhere on the map to log a new issue": "Haz clic en cualquier parte del mapa para registrar un nuevo problema",
      "Map Legend": "Leyenda del Mapa",
      "Reported": "Reportado",
      "Verified": "Verificado",
      "In Progress": "En Progreso",
      "Resolved": "Resuelto",
      "Pothole": "Bache",
      "Water Leak": "Fuga de Agua",
      "Broken Streetlight": "Luz de Calle Rota",
      "Trash & Dumping": "Basura y Vertedero",
      "Graffiti": "Grafiti",
      "Other": "Otro",
      "Low": "Bajo",
      "Medium": "Medio",
      "High": "Alto",
      "Critical": "Crítico",
      "Sign Out": "Cerrar Sesión",
      "Verifications": "Verificaciones",
      "Verify Issue": "Verificar Problema",
      "Update Status": "Actualizar Estado",
      "Speak": "Hablar",
      "Listen": "Escuchar",
      "Translate": "Traducir",
      "Photo Attachment": "Foto Adjunta",
      "Voice note attached": "Nota de voz adjunta",
      "No issues matching filters": "No hay problemas que coincidan con los filtros",
      "Try changing your filters or report a new issue directly on the map.": "Intenta cambiar tus filtros o reporta un nuevo problema directamente en el mapa.",
      "Click directly on the interactive grid map on the right to pinpoint a precise location, or file an instant report.": "Haz clic directamente en el mapa de cuadrícula interactivo a la derecha para señalar una ubicación precisa, o presenta un reporte instantáneo.",
      "Austin Civic Center": "Centro Cívico de Austin",
      "Recommended Action": "Acción Recomendada",
      "Points": "Puntos",
      "Your Level": "Tu Nivel",
      "Active Reports": "Reportes Activos",
      "Leaderboard": "Tabla de Clasificación",
      "Badges Earned": "Insignias Ganadas",
      "Earn rewards by reporting and verifying neighborhood issues. Become a localized community hero!": "¡Gana recompensas reportando y verificando problemas del vecindario. Conviértete en un héroe comunitario local!",
      "Sign in to start earning points, tracking achievements, and verifying issues!": "¡Inicia sesión para comenzar a ganar puntos, rastrear logros y verificar problemas!",
      "Description": "Descripción",
      "Location Name": "Nombre de la Ubicación",
      "Civic Impact Analytics": "Análisis de Impacto Cívico",
      "Report New Civic Issue": "Reportar Nuevo Problema Cívico",
      "Title": "Título",
      "Category": "Categoría",
      "Urgency": "Urgencia",
      "Submit Report": "Enviar Reporte",
      "Cancel": "Cancelar",
      "Audio Notes": "Notas de Audio",
      "Speech to Text Input": "Entrada de Voz a Texto",
      "Listen (Voice Note)": "Escuchar (Nota de Voz)",
      "Recording...": "Grabando...",
      "Translate Issue Details": "Traducir Detalles del Problema",
      "Track Your Points & Badges": "Rastrear Tus Puntos e Insignias",
      "Create an account or sign in as Guest to earn XP for filing reports, verifying issues, and repairing local city infrastructure!": "¡Crea una cuenta o inicia sesión como Invitado para ganar XP por presentar reportes, verificar problemas y reparar la infraestructura de la ciudad local!",
      "Sign In / Open Hero Panel": "Iniciar Sesión / Abrir Panel de Héroe",
      "Active Level": "Nivel Activo",
      "Rank: Level": "Rango: Nivel",
      "PROGRESS TO LEVEL": "PROGRESO AL NIVEL",
      "Earn": "Gana",
      "more XP": "más XP",
      "to level up and unlock exclusive city profile styles!": "para subir de nivel y desbloquear estilos de perfil de la ciudad exclusivos!",
      "My Civic Achievements": "Mis Logros Cívicos",
      "First Step": "Primer Paso",
      "Rookie Reporter": "Reportero Novato",
      "Civic Champion": "Campeón Cívico",
      "Eagle Eye": "Ojo de Águila",
      "Elite Validator": "Validador de Élite",
      "Problem Solver": "Solucionador de Problemas",
      "Neighborhood Guardian": "Guardián del Vecindario",
      "Super Citizen": "Súper Ciudadano",
      "Welcome Bonus: Initial registration into the Austin Civic Network.": "Bono de Bienvenida: Registro inicial en la Red Cívica de Austin.",
      "Logged your first civic issue! The city appreciates your keen eyes.": "¡Registraste tu primer problema cívico! La ciudad aprecia tus ojos atentos.",
      "Reported 5 or more distinct active civic maintenance issues.": "Reportó 5 o más problemas de mantenimiento cívico activos distintos.",
      "Validated another user's report. Helping maintain grid integrity.": "Validó el reporte de otro usuario. Ayudando a mantener la integridad de la cuadrícula.",
      "Verified 5 or more distinct reports to assist civic municipal crews.": "Verificó 5 o más reportes distintos para ayudar a los equipos municipales cívicos.",
      "Successfully had one of your reported issues marked as 'Resolved'.": "Logró con éxito que uno de sus problemas reportados fuera marcado como 'Resuelto'.",
      "Eclipsed 200 total civic contribution experience points.": "Superó los 200 puntos de experiencia de contribución cívica total.",
      "Exceeded 500 total points. Legendary status in our Austin metro grid.": "Excedió los 500 puntos totales. Estatus legendario en nuestra cuadrícula metropolitana de Austin.",
      "Special achievement earned for helping the city.": "Logro especial obtenido por ayudar a la ciudad.",
      "Reports": "Reportes",
      "Logged Reports": "Reportes Registrados",
      "Issues Resolved": "Problemas Resueltos",
      "Active Heroes": "Héroes Activos",
      "Top Contributors": "Principales Contribuyentes",
      "No active citizens yet. Be the first to report an issue!": "Aún no hay ciudadanos activos. ¡Sé el primero en reportar un problema!",
      "Issues Status Breakdown": "Desglose del Estado de los Problemas",
      "Reports by Category": "Reportes por Categoría",
      "Activity Trend (Last 7 Days)": "Tendencia de Actividad (Últimos 7 Días)",
      "Gemini Multimodal Reporter": "Reportero Multimodal de Gemini",
      "You can upload a photo of the issue, record an audio description, or type what you see. The Gemini API will automatically categorize, name, and assess the urgency of the report.": "Puedes subir una foto del problema, grabar una descripción de audio o escribir lo que ves. La API de Gemini clasificará, nombrará y evaluará automáticamente la urgencia del reporte.",
      "What is the issue? (Optional if uploading photo or voice)": "¿Cuál es el problema? (Opcional si subes foto o voz)",
      "Listening...": "Escuchando...",
      "Dictate": "Dictar",
      "Add Photo Evidence": "Agregar Evidencia Fotográfica",
      "Drag and drop or click to upload": "Arrastra y suelta o haz clic para subir",
      "Record Voice Note": "Grabar Nota de Voz",
      "Recording live mic...": "Grabando micrófono en vivo...",
      "Stop Recording": "Detener Grabación",
      "Start Mic Recording": "Iniciar Grabación de Micrófono",
      "Speak and describe the issue out loud instead of writing it!": "¡Habla y describe el problema en voz alta en lugar de escribirlo!",
      "Write Manually Instead": "Escribir Manualmente en su Lugar",
      "Gemini Analyzing...": "Gemini Analizando...",
      "Analyze with Gemini AI": "Analizar con Gemini AI",
      "Simulation Mode Active": "Modo de Simulación Activo",
      "Gemini Analysis Succeeded!": "¡Análisis de Gemini Exitoso!",
      "Calculated a high-quality analysis simulation. Configure GEMINI_API_KEY in Secrets for live multimodal Gemini AI.": "Simulación de análisis de alta calidad calculada. Configura GEMINI_API_KEY en Secrets para usar Gemini AI multimodal en vivo.",
      "Gemini analyzed your multimodal report and extracted the parameters below! Feel free to review and adjust.": "¡Gemini analizó tu reporte multimodal y extrajo los parámetros a continuación! Siéntete libre de revisar y ajustar.",
      "Issue Title": "Título del Problema",
      "Urgency Level": "Nivel de Urgencia",
      "Location / Address": "Ubicación / Dirección",
      "Dispatch Recommendations (For Civil Crews)": "Recomendaciones de Despacho (Para Equipos Civiles)",
      "Go Back": "Volver",
      "Submit Civic Report": "Enviar Reporte Cívico",
      "or continue with": "o continuar con",
      "Enter as Guest / Try Demo": "Ingresar como Invitado / Probar Demo",
      "Join citizens repairing and tracking local civic issues": "Únete a los ciudadanos que reparan y rastrean problemas cívicos locales",
      "Your Name": "Tu Nombre",
      "Email Address": "Correo Electrónico",
      "Password": "Contraseña",
      "Create Hero Account": "Crear Cuenta de Héroe",
      "Sign In": "Iniciar Sesión",
      "All Statuses": "Todos los Estados",
      "Stop Reading": "Detener Lectura",
      "Translating...": "Traduciendo...",
      "Show Original": "Mostrar Original",
      "Verified By You": "Verificado por Ti",
      "Verifying...": "Verificando...",
      "Live Google Maps": "Google Maps en Vivo",
      "Custom Interactive Grid": "Cuadrícula Interactiva Personalizada",
      "File a Civic Report": "Presentar un Reporte Cívico",
      "Coordinate": "Coordenada"
  },
  vi: {
      "Community Hero": "Anh Hùng Cộng Đồng",
      "Civic Action Platform": "Nền Tảng Hành Động Dân Sự",
      "Civic Map & Grid": "Bản Đồ & Lưới Dân Sự",
      "Impact Analytics": "Phân Tích Tác Động",
      "Sign In / Join": "Đăng Nhập / Tham Gia",
      "Notice a civic issue?": "Phát hiện vấn đề công cộng?",
      "File Quick Civic Report": "Gửi Báo Cáo Nhanh",
      "Active Civic Reports": "Báo Cáo Công Cộng Hoạt Động",
      "Austin Civic Grid": "Lưới Dân Sự Austin",
      "Click anywhere on the map to log a new issue": "Nhấp vào bất kỳ đâu trên bản đồ để báo cáo sự cố mới",
      "Map Legend": "Chú Giải Bản Đồ",
      "Reported": "Đã Báo Cáo",
      "Verified": "Đã Xác Minh",
      "In Progress": "Đang Xử Lý",
      "Resolved": "Đã Giải Quyết",
      "Pothole": "Ổ Gà",
      "Water Leak": "Rò Rỉ Nước",
      "Broken Streetlight": "Đèn Đường Hỏng",
      "Trash & Dumping": "Rác Thải & Đổ Trộm",
      "Graffiti": "Graffiti",
      "Other": "Khác",
      "Low": "Thấp",
      "Medium": "Trung Bình",
      "High": "Cao",
      "Critical": "Nghiêm Trọng",
      "Sign Out": "Đăng Xuất",
      "Verifications": "Xác Minh",
      "Verify Issue": "Xác Minh Sự Cố",
      "Update Status": "Cập Nhật Trạng Thái",
      "Speak": "Đọc",
      "Listen": "Lắng Nghe (STT)",
      "Translate": "Dịch",
      "Photo Attachment": "Ảnh Đính Kèm",
      "Voice note attached": "Ghi âm đính kèm",
      "No issues matching filters": "Không có sự cố nào khớp với bộ lọc",
      "Try changing your filters or report a new issue directly on the map.": "Hãy thử thay đổi bộ lọc hoặc báo cáo sự cố mới trực tiếp trên bản đồ.",
      "Click directly on the interactive grid map on the right to pinpoint a precise location, or file an instant report.": "Nhấp trực tiếp vào bản đồ lưới tương tác bên phải để xác định vị trí chính xác hoặc gửi báo cáo ngay lập tức.",
      "Austin Civic Center": "Trung Tâm Dân Sự Austin",
      "Recommended Action": "Hành Động Khuyến Nghị",
      "Points": "Điểm",
      "Your Level": "Cấp Độ Của Bạn",
      "Active Reports": "Báo Cáo Hoạt Động",
      "Leaderboard": "Bảng Xếp Hạng",
      "Badges Earned": "Huy Hiệu Đạt Được",
      "Earn rewards by reporting and verifying neighborhood issues. Become a localized community hero!": "Nhận phần thưởng bằng cách báo cáo và xác minh các vấn đề trong khu phố. Trở thành anh hùng cộng đồng địa phương!",
      "Sign in to start earning points, tracking achievements, and verifying issues!": "Đăng nhập để bắt đầu tích lũy điểm, theo dõi thành tích và xác minh sự cố!",
      "Description": "Mô Tả",
      "Location Name": "Tên Địa Điểm",
      "Civic Impact Analytics": "Phân Tích Tác Động Dân Sự",
      "Report New Civic Issue": "Báo Cáo Sự Cố Công Cộng Mới",
      "Title": "Tiêu Đề",
      "Category": "Danh Mục",
      "Urgency": "Độ Khẩn Cấp",
      "Submit Report": "Gửi Báo Cáo",
      "Cancel": "Hủy",
      "Audio Notes": "Ghi Chú Âm Thanh",
      "Speech to Text Input": "Nhập Giọng Nói Thành Văn Bản",
      "Listen (Voice Note)": "Nghe (Ghi Âm)",
      "Recording...": "Đang ghi âm...",
      "Translate Issue Details": "Dịch Chi Tiết Sự Cố",
      "Track Your Points & Badges": "Theo Dõi Điểm & Huy Hiệu",
      "Create an account or sign in as Guest to earn XP for filing reports, verifying issues, and repairing local city infrastructure!": "Tạo tài khoản hoặc đăng nhập với tư cách Khách để kiếm XP cho việc gửi báo cáo, xác minh sự cố và sửa chữa cơ sở hạ tầng thành phố địa phương!",
      "Sign In / Open Hero Panel": "Đăng Nhập / Mở Bảng Anh Hùng",
      "Active Level": "Cấp Độ Hoạt Động",
      "Rank: Level": "Xếp Hạng: Cấp Độ",
      "PROGRESS TO LEVEL": "TIẾN TRÌNH LÊN CẤP",
      "Earn": "Kiếm",
      "more XP": "thêm XP",
      "to level up and unlock exclusive city profile styles!": "để lên cấp và mở khóa các phong cách hồ sơ thành phố độc quyền!",
      "My Civic Achievements": "Thành Tích Dân Sự Của Tôi",
      "First Step": "Bước Đầu Tiên",
      "Rookie Reporter": "Phóng Viên Tập Sự",
      "Civic Champion": "Nhà Vô Địch Dân Sự",
      "Eagle Eye": "Mắt Đại Bàng",
      "Elite Validator": "Trình Xác Minh Ưu Tú",
      "Problem Solver": "Người Giải Quyết Vấn Đề",
      "Neighborhood Guardian": "Người Bảo Vệ Khu Phố",
      "Super Citizen": "Siêu Công Dân",
      "Welcome Bonus: Initial registration into the Austin Civic Network.": "Thưởng Chào Mừng: Đăng ký ban đầu vào Mạng Lưới Dân Sự Austin.",
      "Logged your first civic issue! The city appreciates your keen eyes.": "Đã ghi nhận sự cố dân sự đầu tiên của bạn! Thành phố đánh giá cao sự tinh mắt của bạn.",
      "Reported 5 or more distinct active civic maintenance issues.": "Đã báo cáo từ 5 sự cố bảo trì công cộng hoạt động khác nhau trở lên.",
      "Validated another user's report. Helping maintain grid integrity.": "Đã xác minh báo cáo của người dùng khác. Giúp duy trì tính toàn vẹn của hệ thống.",
      "Verified 5 or more distinct reports to assist civic municipal crews.": "Đã xác minh từ 5 báo cáo khác nhau trở lên để hỗ trợ các đội ngũ thành phố.",
      "Successfully had one of your reported issues marked as 'Resolved'.": "Một trong các sự cố bạn báo cáo đã được đánh dấu thành công là 'Đã giải quyết'.",
      "Eclipsed 200 total civic contribution experience points.": "Vượt mốc tổng cộng 200 điểm kinh nghiệm đóng góp dân sự.",
      "Exceeded 500 total points. Legendary status in our Austin metro grid.": "Vượt quá tổng cộng 500 điểm. Trở thành huyền thoại trong lưới dân sự Austin.",
      "Special achievement earned for helping the city.": "Đạt được thành tích đặc biệt vì đã giúp đỡ thành phố.",
      "Reports": "Báo Cáo",
      "Logged Reports": "Báo Cáo Đã Ghi Nhận",
      "Issues Resolved": "Sự Cố Đã Giải Quyết",
      "Active Heroes": "Anh Hùng Hoạt Động",
      "Top Contributors": "Những Người Đóng Góp Hàng Đầu",
      "No active citizens yet. Be the first to report an issue!": "Chưa có công dân hoạt động nào. Hãy là người đầu tiên báo cáo sự cố!",
      "Issues Status Breakdown": "Phân Tích Trạng Thái Sự Cố",
      "Reports by Category": "Báo Cáo Theo Danh Mục",
      "Activity Trend (Last 7 Days)": "Xu Hướng Hoạt Động (7 Ngày Qua)",
      "Gemini Multimodal Reporter": "Báo Cáo Đa Phương Tiện Gemini",
      "You can upload a photo of the issue, record an audio description, or type what you see. The Gemini API will automatically categorize, name, and assess the urgency of the report.": "Bạn có thể tải ảnh chụp sự cố lên, ghi âm mô tả hoặc nhập những gì bạn nhìn thấy. Gemini API sẽ tự động phân loại, đặt tên và đánh giá mức độ khẩn cấp của báo cáo.",
      "What is the issue? (Optional if uploading photo or voice)": "Sự cố là gì? (Tùy chọn nếu tải lên ảnh hoặc giọng nói)",
      "Listening...": "Đang lắng nghe...",
      "Dictate": "Đọc giọng nói",
      "Add Photo Evidence": "Thêm Bằng Chứng Ảnh",
      "Drag and drop or click to upload": "Kéo và thả hoặc nhấp để tải lên",
      "Record Voice Note": "Ghi Âm Mô Tả",
      "Recording live mic...": "Đang ghi âm trực tiếp...",
      "Stop Recording": "Dừng Ghi Âm",
      "Start Mic Recording": "Bắt Đầu Ghi Âm",
      "Speak and describe the issue out loud instead of writing it!": "Hãy nói và mô tả to rõ sự cố thay vì viết nó!",
      "Write Manually Instead": "Thay Thế Bằng Nhập Thủ Công",
      "Gemini Analyzing...": "Gemini Đang Phân Tích...",
      "Analyze with Gemini AI": "Phân Tích Bằng Gemini AI",
      "Simulation Mode Active": "Chế Độ Mô Phỏng Hoạt Động",
      "Gemini Analysis Succeeded!": "Phân Tích Của Gemini Đã Thành Công!",
      "Calculated a high-quality analysis simulation. Configure GEMINI_API_KEY in Secrets for live multimodal Gemini AI.": "Đã tính toán mô phỏng phân tích chất lượng cao. Định cấu hình GEMINI_API_KEY trong Secrets để chạy Gemini AI đa phương tiện trực tiếp.",
      "Gemini analyzed your multimodal report and extracted the parameters below! Feel free to review and adjust.": "Gemini đã phân tích báo cáo đa phương tiện của bạn và trích xuất các thông số bên dưới! Hãy thoải mái xem xét và điều chỉnh.",
      "Issue Title": "Tiêu Đề Sự Cố",
      "Urgency Level": "Mức Độ Khẩn Cấp",
      "Location / Address": "Vị Trí / Địa Chỉ",
      "Dispatch Recommendations (For Civil Crews)": "Khuyến Nghị Điều Phối (Cho Đội Ngũ Dân Sự)",
      "Go Back": "Quay Lại",
      "Submit Civic Report": "Gửi Báo Cáo Công Cộng",
      "or continue with": "hoặc tiếp tục với",
      "Enter as Guest / Try Demo": "Vào với tư cách Khách / Thử Bản Demo",
      "Join citizens repairing and tracking local civic issues": "Tham gia cùng các công dân sửa chữa và theo dõi các vấn đề dân sự địa phương",
      "Your Name": "Tên của bạn",
      "Email Address": "Địa chỉ Email",
      "Password": "Mật khẩu",
      "Create Hero Account": "Tạo Tài Khoản Anh Hùng",
      "Sign In": "Đăng Nhập",
      "All Statuses": "Tất cả Trạng thái",
      "Stop Reading": "Dừng Đọc",
      "Translating...": "Đang dịch...",
      "Show Original": "Hiển thị Bản gốc",
      "Verified By You": "Đã Xác Minh Bởi Bạn",
      "Verifying...": "Đang xác minh...",
      "Live Google Maps": "Google Maps Trực tiếp",
      "Custom Interactive Grid": "Bản đồ Lưới Tương tác",
      "File a Civic Report": "Gửi Báo Cáo Công Cộng",
      "Coordinate": "Tọa độ"
  },
  hi: {
      "Community Hero": "कम्युनिटी हीरो",
      "Civic Action Platform": "नागरिक कार्रवाई मंच",
      "Civic Map & Grid": "नागरिक मानचित्र और ग्रिड",
      "Impact Analytics": "प्रभाव विश्लेषण",
      "Sign In / Join": "साइन इन / शामिल हों",
      "Notice a civic issue?": "क्या आपने कोई नागरिक समस्या देखी?",
      "File Quick Civic Report": "त्वरित नागरिक रिपोर्ट दर्ज करें",
      "Active Civic Reports": "सक्रिय नागरिक रिपोर्ट",
      "Austin Civic Grid": "ऑस्टिन नागरिक ग्रिड",
      "Click anywhere on the map to log a new issue": "नया मुद्दा दर्ज करने के लिए मानचित्र पर कहीं भी क्लिक करें",
      "Map Legend": "मानचित्र सूची",
      "Reported": "रिपोर्ट किया गया",
      "Verified": "सत्यापित",
      "In Progress": "प्रगति पर",
      "Resolved": "हल हो गया",
      "Pothole": "सड़क का गड्ढा",
      "Water Leak": "पानी का रिसाव",
      "Broken Streetlight": "टूटी स्ट्रीटलाइट",
      "Trash & Dumping": "कचरा और डंपिंग",
      "Graffiti": "ग्राफिटी",
      "Other": "अन्य",
      "Low": "कम",
      "Medium": "मध्यम",
      "High": "उच्च",
      "Critical": "गंभीर",
      "Sign Out": "साइन आउट",
      "Verifications": "सत्यापन",
      "Verify Issue": "मुद्दे को सत्यापित करें",
      "Update Status": "स्थिति अपडेट करें",
      "Speak": "बोलें",
      "Listen": "सुनें (STT)",
      "Translate": "अनुवाद करें",
      "Photo Attachment": "फोटो संलग्नक",
      "Voice note attached": "आवाज नोट संलग्न है",
      "No issues matching filters": "फ़िल्टर से मेल खाने वाले कोई मुद्दे नहीं हैं",
      "Try changing your filters or report a new issue directly on the map.": "अपने फ़िल्टर बदलने का प्रयास करें या सीधे मानचित्र पर एक नया मुद्दा रिपोर्ट करें।",
      "Click directly on the interactive grid map on the right to pinpoint a precise location, or file an instant report.": "सटीक स्थान को इंगित करने के लिए दाईं ओर इंटरैक्टिव ग्रिड मानचित्र पर सीधे क्लिक करें, या तुरंत रिपोर्ट दर्ज करें।",
      "Austin Civic Center": "ऑस्टिन नागरिक केंद्र",
      "Recommended Action": "अनुशंसित कार्रवाई",
      "Points": "अंक",
      "Your Level": "आपका स्तर",
      "Active Reports": "सक्रिय रिपोर्ट",
      "Leaderboard": "लीडरबोर्ड",
      "Badges Earned": "अर्जित बैज",
      "Earn rewards by reporting and verifying neighborhood issues. Become a localized community hero!": "पड़ोस के मुद्दों की रिपोर्टिंग और सत्यापन करके पुरस्कार अर्जित करें। स्थानीय समुदाय के नायक बनें!",
      "Sign in to start earning points, tracking achievements, and verifying issues!": "अंक अर्जित करने, उपलब्धियों को ट्रैक करने और मुद्दों को सत्यापित करने के लिए साइन इन करें!",
      "Description": "विवरण",
      "Location Name": "स्थान का नाम",
      "Civic Impact Analytics": "नागरिक प्रभाव विश्लेषण",
      "Report New Civic Issue": "नया नागरिक मुद्दा रिपोर्ट करें",
      "Title": "शीर्षक",
      "Category": "श्रेणी",
      "Urgency": "अत्यावश्यकता",
      "Submit Report": "रिपोर्ट प्रस्तुत करें",
      "Cancel": "रद्द करें",
      "Audio Notes": "ऑडियो नोट्स",
      "Speech to Text Input": "आवाज से पाठ इनपुट",
      "Listen (Voice Note)": "सुनें (आवाज नोट)",
      "Recording...": "रिकॉर्डिंग हो रही है...",
      "Translate Issue Details": "विवरण अनुवाद करें",
      "Track Your Points & Badges": "अपने अंक और बैज ट्रैक करें",
      "Create an account or sign in as Guest to earn XP for filing reports, verifying issues, and repairing local city infrastructure!": "रिपोर्ट दर्ज करने, मुद्दों को सत्यापित करने और स्थानीय शहर के बुनियादी ढांचे की मरम्मत के लिए XP अर्जित करने के लिए एक खाता बनाएं या अतिथि के रूप में साइन इन करें!",
      "Sign In / Open Hero Panel": "साइन इन / हीरो पैनल खोलें",
      "Active Level": "सक्रिय स्तर",
      "Rank: Level": "रैंक: स्तर",
      "PROGRESS TO LEVEL": "स्तर के लिए प्रगति",
      "Earn": "अर्जित करें",
      "more XP": "अधिक XP",
      "to level up and unlock exclusive city profile styles!": "लेवल अप करने और विशेष शहर प्रोफ़ाइल शैलियों को अनलॉक करने के लिए!",
      "My Civic Achievements": "मेरी नागरिक उपलब्धियां",
      "First Step": "पहला कदम",
      "Rookie Reporter": "नौसिखिया रिपोर्टर",
      "Civic Champion": "नागरिक चैंपियन",
      "Eagle Eye": "चील की नजर",
      "Elite Validator": "अभिजात वर्ग सत्यापनकर्ता",
      "Problem Solver": "समस्या समाधानकर्ता",
      "Neighborhood Guardian": "पड़ोस का रक्षक",
      "Super Citizen": "सुपर नागरिक",
      "Welcome Bonus: Initial registration into the Austin Civic Network.": "स्वागत बोनस: ऑस्टिन नागरिक नेटवर्क में प्रारंभिक पंजीकरण।",
      "Logged your first civic issue! The city appreciates your keen eyes.": "अपना पहला नागरिक मुद्दा दर्ज किया! शहर आपकी पैनी नजरों की सराहना करता है।",
      "Reported 5 or more distinct active civic maintenance issues.": "5 या अधिक विभिन्न सक्रिय नागरिक रखरखाव मुद्दों की रिपोर्ट की।",
      "Validated another user's report. Helping maintain grid integrity.": "किसी अन्य उपयोगकर्ता की रिपोर्ट को सत्यापित किया। ग्रिड अखंडता बनाए रखने में मदद कर रहा है।",
      "Verified 5 or more distinct reports to assist civic municipal crews.": "नागरिक नगर निगम के कर्मचारियों की सहायता के लिए 5 या अधिक विभिन्न रिपोर्टों को सत्यापित किया।",
      "Successfully had one of your reported issues marked as 'Resolved'.": "सफलतापूर्वक आपके रिपोर्ट किए गए मुद्दों में से एक को 'हल' के रूप में चिह्नित किया गया।",
      "Eclipsed 200 total civic contribution experience points.": "कुल 200 नागरिक योगदान अनुभव अंक पार कर लिए।",
      "Exceeded 500 total points. Legendary status in our Austin metro grid.": "कुल 500 अंकों से अधिक। हमारे ऑस्टिन मेट्रो ग्रिड में महान स्थिति।",
      "Special achievement earned for helping the city.": "शहर की मदद के लिए अर्जित विशेष उपलब्धि।",
      "Reports": "रिपोर्ट",
      "Logged Reports": "दर्ज की गई रिपोर्ट",
      "Issues Resolved": "हल किए गए मुद्दे",
      "Active Heroes": "सक्रिय नायक",
      "Top Contributors": "शीर्ष योगदानकर्ता",
      "No active citizens yet. Be the first to report an issue!": "अभी तक कोई सक्रिय नागरिक नहीं हैं। समस्या की रिपोर्ट करने वाले पहले व्यक्ति बनें!",
      "Issues Status Breakdown": "मुद्दों की स्थिति का विवरण",
      "Reports by Category": "श्रेणी के अनुसार रिपोर्ट",
      "Activity Trend (Last 7 Days)": "गतिविधि प्रवृत्ति (पिछले 7 दिन)",
      "Gemini Multimodal Reporter": "जेमिनी मल्टीमॉडल रिपोर्टर",
      "You can upload a photo of the issue, record an audio description, or type what you see. The Gemini API will automatically categorize, name, and assess the urgency of the report.": "आप मुद्दे की एक तस्वीर अपलोड कर सकते हैं, एक ऑडियो विवरण रिकॉर्ड कर सकते हैं, या जो आप देखते हैं उसे टाइप कर सकते हैं। जेमिनी एपीआई स्वचालित रूप से श्रेणीबद्ध, नाम और रिपोर्ट की अत्यावश्यकता का आकलन करेगी।",
      "What is the issue? (Optional if uploading photo or voice)": "मुद्दा क्या है? (फोटो या आवाज अपलोड करने पर वैकल्पिक)",
      "Listening...": "सुन रहा है...",
      "Dictate": "डिक्टेट करें",
      "Add Photo Evidence": "फोटो सबूत जोड़ें",
      "Drag and drop or click to upload": "अपलोड करने के लिए खींचें और छोड़ें या क्लिक करें",
      "Record Voice Note": "आवाज नोट रिकॉर्ड करें",
      "Recording live mic...": "लाइव माइक रिकॉर्डिंग हो रही है...",
      "Stop Recording": "रिकॉर्डिंग रोकें",
      "Start Mic Recording": "माइक रिकॉर्डिंग शुरू करें",
      "Speak and describe the issue out loud instead of writing it!": "इसे लिखने के बजाय जोर से बोलें और मुद्दे का वर्णन करें!",
      "Write Manually Instead": "इसके बजाय मैन्युअल रूप से लिखें",
      "Gemini Analyzing...": "जेमिनी विश्लेषण कर रहा है...",
      "Analyze with Gemini AI": "जेमिनी एआई के साथ विश्लेषण करें",
      "Simulation Mode Active": "सिम्युलेशन मोड सक्रिय है",
      "Gemini Analysis Succeeded!": "जेमिनी विश्लेषण सफल रहा!",
      "Calculated a high-quality analysis simulation. Configure GEMINI_API_KEY in Secrets for live multimodal Gemini AI.": "एक उच्च गुणवत्ता वाले विश्लेषण सिमुलेशन की गणना की गई। लाइव मल्टीमॉडल जेमिनी एआई के लिए सीक्रेट्स में GEMINI_API_KEY कॉन्फ़िगर करें।",
      "Gemini analyzed your multimodal report and extracted the parameters below! Feel free to review and adjust.": "जेमिनी ने आपकी मल्टीमॉडल रिपोर्ट का विश्लेषण किया और नीचे दिए गए मापदंडों को निकाला! समीक्षा करने और समायोजित करने के लिए स्वतंत्र महसूस करें।",
      "Issue Title": "मुद्दे का शीर्षक",
      "Urgency Level": "अत्यावश्यकता स्तर",
      "Location / Address": "स्थान / पता",
      "Dispatch Recommendations (For Civil Crews)": "प्रेषण सिफारिशें (नागरिक कर्मचारियों के लिए)",
      "Go Back": "वापस जाएं",
      "Submit Civic Report": "नागरिक रिपोर्ट प्रस्तुत करें",
      "or continue with": "या इसके साथ जारी रखें",
      "Enter as Guest / Try Demo": "अतिथि के रूप में प्रवेश करें / डेमो का प्रयास करें",
      "Join citizens repairing and tracking local civic issues": "स्थानीय नागरिक मुद्दों की मरम्मत और ट्रैकिंग करने वाले नागरिकों में शामिल हों",
      "Your Name": "आपका नाम",
      "Email Address": "ईमेल पता",
      "Password": "पासवर्ड",
      "Create Hero Account": "हीरो खाता बनाएं",
      "Sign In": "साइन इन करें",
      "All Statuses": "सभी स्थितियां",
      "Stop Reading": "पढ़ना बंद करें",
      "Translating...": "अनुवाद किया जा रहा है...",
      "Show Original": "मूल दिखाएं",
      "Verified By You": "आपके द्वारा सत्यापित",
      "Verifying...": "सत्यापित किया जा रहा है...",
      "Live Google Maps": "लाइव गूगल मैप्स",
      "Custom Interactive Grid": "कस्टम इंटरैक्टिव ग्रिड",
      "File a Civic Report": "नागरिक रिपोर्ट दर्ज करें",
      "Coordinate": "निर्देशांक"
  },
  zh: {
      "Community Hero": "社区英雄",
      "Civic Action Platform": "公民行动平台",
      "Civic Map & Grid": "公民地图与网格",
      "Impact Analytics": "影响分析",
      "Sign In / Join": "登录 / 加入",
      "Notice a civic issue?": "发现市政问题？",
      "File Quick Civic Report": "提交快速报告",
      "Active Civic Reports": "活跃市政报告",
      "Austin Civic Grid": "奥斯汀市政网格",
      "Click anywhere on the map to log a new issue": "点击地图上的任意位置记录新问题",
      "Map Legend": "地图图例",
      "Reported": "已报告",
      "Verified": "已验证",
      "In Progress": "处理中",
      "Resolved": "已解决",
      "Pothole": "道路坑洼",
      "Water Leak": "漏水",
      "Broken Streetlight": "路灯损坏",
      "Trash & Dumping": "垃圾与非法倾倒",
      "Graffiti": "涂鸦",
      "Other": "其他",
      "Low": "低",
      "Medium": "中",
      "High": "高",
      "Critical": "危急",
      "Sign Out": "退出登录",
      "Verifications": "验证数",
      "Verify Issue": "验证此问题",
      "Update Status": "更新状态",
      "Speak": "朗读",
      "Listen": "语音输入 (STT)",
      "Translate": "翻译",
      "Photo Attachment": "照片附件",
      "Voice note attached": "附带语音留言",
      "No issues matching filters": "没有符合过滤条件的问题",
      "Try changing your filters or report a new issue directly on the map.": "尝试更改过滤器或直接在地图上报告新问题。",
      "Click directly on the interactive grid map on the right to pinpoint a precise location, or file an instant report.": "直接点击右侧的交互式网格地图以精确定位，或提交即时报告。",
      "Austin Civic Center": "奥斯汀市政中心",
      "Recommended Action": "建议措施",
      "Points": "积分",
      "Your Level": "您的等级",
      "Active Reports": "活跃报告",
      "Leaderboard": "排行榜",
      "Badges Earned": "获得徽章",
      "Earn rewards by reporting and verifying neighborhood issues. Become a localized community hero!": "通过报告和核实社区问题赚取奖励。成为当地的社区英雄！",
      "Sign in to start earning points, tracking achievements, and verifying issues!": "登录以开始赚取积分、跟踪成就并验证问题！",
      "Description": "问题描述",
      "Location Name": "地点名称",
      "Civic Impact Analytics": "公民影响分析",
      "Report New Civic Issue": "报告新市政问题",
      "Title": "标题",
      "Category": "类别",
      "Urgency": "紧急程度",
      "Submit Report": "提交报告",
      "Cancel": "取消",
      "Audio Notes": "音频笔记",
      "Speech to Text Input": "语音转文本输入",
      "Listen (Voice Note)": "听（语音留言）",
      "Recording...": "录音中...",
      "Translate Issue Details": "翻译详情",
      "Track Your Points & Badges": "追踪积分与徽章",
      "Create an account or sign in as Guest to earn XP for filing reports, verifying issues, and repairing local city infrastructure!": "创建账户或以访客身份登录以赚取提交报告、验证问题和修理本地基础设施的经验值！",
      "Sign In / Open Hero Panel": "登录 / 打开英雄面板",
      "Active Level": "活跃等级",
      "Rank: Level": "级别：等级",
      "PROGRESS TO LEVEL": "升级进度",
      "Earn": "赚取",
      "more XP": "更多经验值",
      "to level up and unlock exclusive city profile styles!": "以升级并解锁专属城市个人资料样式！",
      "My Civic Achievements": "我的市政成就",
      "First Step": "第一步",
      "Rookie Reporter": "新手报告员",
      "Civic Champion": "市民冠军",
      "Eagle Eye": "鹰眼",
      "Elite Validator": "精英验证者",
      "Problem Solver": "问题解决者",
      "Neighborhood Guardian": "社区守护者",
      "Super Citizen": "超级市民",
      "Welcome Bonus: Initial registration into the Austin Civic Network.": "欢迎奖励：注册加入奥斯汀市民网络。",
      "Logged your first civic issue! The city appreciates your keen eyes.": "记录了您的第一个市民问题！城市感谢您的敏锐眼光。",
      "Reported 5 or more distinct active civic maintenance issues.": "报告了5个或更多不同的活跃市政维护问题。",
      "Validated another user's report. Helping maintain grid integrity.": "验证了另一位用户的报告。帮助维护网格完整性。",
      "Verified 5 or more distinct reports to assist civic municipal crews.": "验证了5个或更多不同的报告，以协助市政公用人员。",
      "Successfully had one of your reported issues marked as 'Resolved'.": "成功使您报告的问题之一被标记为“已解决”。",
      "Eclipsed 200 total civic contribution experience points.": "超越200点总市民贡献经验值。",
      "Exceeded 500 total points. Legendary status in our Austin metro grid.": "超过500总积分。在我们奥斯汀都市网格中的传奇地位。",
      "Special achievement earned for helping the city.": "因帮助城市而获得特别成就。",
      "Reports": "报告",
      "Logged Reports": "已记录的报告",
      "Issues Resolved": "已解决的问题",
      "Active Heroes": "活跃英雄",
      "Top Contributors": "杰出贡献者",
      "No active citizens yet. Be the first to report an issue!": "暂无活跃市民。成为第一个报告问题的人！",
      "Issues Status Breakdown": "问题状态分类",
      "Reports by Category": "按类别统计的报告",
      "Activity Trend (Last 7 Days)": "活动趋势（最近7天）",
      "Gemini Multimodal Reporter": "Gemini 多模态报告员",
      "You can upload a photo of the issue, record an audio description, or type what you see. The Gemini API will automatically categorize, name, and assess the urgency of the report.": "您可以上传问题照片、录制语音描述，或输入您所看到的内容。Gemini API 将自动进行分类、命名和评估报告的紧急程度。",
      "What is the issue? (Optional if uploading photo or voice)": "发生了什么问题？（如果上传照片或录音则可选填）",
      "Listening...": "正在倾听...",
      "Dictate": "语音听写",
      "Add Photo Evidence": "添加照片证据",
      "Drag and drop or click to upload": "拖放或点击上传",
      "Record Voice Note": "录制语音留言",
      "Recording live mic...": "录音中...",
      "Stop Recording": "停止录音",
      "Start Mic Recording": "开始录音",
      "Speak and describe the issue out loud instead of writing it!": "大声说出并描述问题，无需手动输入！",
      "Write Manually Instead": "改为手动输入",
      "Gemini Analyzing...": "Gemini 正在分析...",
      "Analyze with Gemini AI": "使用 Gemini AI 分析",
      "Simulation Mode Active": "模拟模式已启用",
      "Gemini Analysis Succeeded!": "Gemini 分析成功！",
      "Calculated a high-quality analysis simulation. Configure GEMINI_API_KEY in Secrets for live multimodal Gemini AI.": "已计算高质量分析模拟。在 Secrets 中配置 GEMINI_API_KEY 以体验实时多模态 Gemini AI。",
      "Gemini analyzed your multimodal report and extracted the parameters below! Feel free to review and adjust.": "Gemini 分析了您的多模态报告并提取了以下参数！您可以随意查看并调整。",
      "Issue Title": "问题标题",
      "Urgency Level": "紧急程度",
      "Location / Address": "位置 / 地址",
      "Dispatch Recommendations (For Civil Crews)": "派遣建议（供公用人员参考）",
      "Go Back": "返回",
      "Submit Civic Report": "提交市政报告",
      "or continue with": "或继续使用",
      "Enter as Guest / Try Demo": "以访客身份进入 / 尝试演示",
      "Join citizens repairing and tracking local civic issues": "加入修理和追踪本地市政问题的市民行列",
      "Your Name": "您的姓名",
      "Email Address": "电子邮箱",
      "Password": "密码",
      "Create Hero Account": "创建英雄账户",
      "Sign In": "登录",
      "All Statuses": "所有状态",
      "Stop Reading": "停止朗读",
      "Translating...": "正在翻译...",
      "Show Original": "显示原文",
      "Verified By You": "您已验证",
      "Verifying...": "正在验证...",
      "Live Google Maps": "实时谷歌地图",
      "Custom Interactive Grid": "自定义交互式网格",
      "File a Civic Report": "提交市政报告",
      "Coordinate": "坐标"
  },
  fr: {
      "Community Hero": "Héros Communautaire",
      "Civic Action Platform": "Plateforme d'Action Civique",
      "Civic Map & Grid": "Carte & Grille Civique",
      "Impact Analytics": "Analyses d'Impact",
      "Sign In / Join": "Se Connecter / Rejoindre",
      "Notice a civic issue?": "Remarquez-vous un problème civique ?",
      "File Quick Civic Report": "Déposer un Signalement Civique Rapide",
      "Active Civic Reports": "Signalements Civiques Actifs",
      "Austin Civic Grid": "Grille Civique d'Austin",
      "Click anywhere on the map to log a new issue": "Cliquez n'importe où sur la carte pour signaler un nouveau problème",
      "Map Legend": "Légende de la Carte",
      "Reported": "Signalé",
      "Verified": "Vérifié",
      "In Progress": "En Cours",
      "Resolved": "Résolu",
      "Pothole": "Nid-de-poule",
      "Water Leak": "Fuite d'Eau",
      "Broken Streetlight": "Réverbère En Panne",
      "Trash & Dumping": "Déchets & Décharge Sauvage",
      "Graffiti": "Graffiti",
      "Other": "Autre",
      "Low": "Faible",
      "Medium": "Moyen",
      "High": "Élevé",
      "Critical": "Critique",
      "Sign Out": "Se Déconnecter",
      "Verifications": "Vérifications",
      "Verify Issue": "Vérifier le Problème",
      "Update Status": "Mettre à Jour le Statut",
      "Speak": "Parler",
      "Listen": "Écouter (STT)",
      "Translate": "Traduire",
      "Photo Attachment": "Photo Jointe",
      "Voice note attached": "Note vocale jointe",
      "No issues matching filters": "Aucun problème ne correspond aux filtres",
      "Try changing your filters or report a new issue directly on the map.": "Essayez de modifier vos filtres ou signalez un nouveau problème directement sur la carte.",
      "Click directly on the interactive grid map on the right to pinpoint a precise location, or file an instant report.": "Cliquez directement sur la carte de grille interactive à droite pour localiser un endroit précis, ou déposez un rapport instantané.",
      "Austin Civic Center": "Centre Civique d'Austin",
      "Recommended Action": "Mesure Recommandée",
      "Points": "Points",
      "Your Level": "Votre Niveau",
      "Active Reports": "Signalements Actifs",
      "Leaderboard": "Tableau de Classement",
      "Badges Earned": "Badges Obtenus",
      "Earn rewards by reporting and verifying neighborhood issues. Become a localized community hero!": "Gagnez des récompenses en signalant et vérifiant les problèmes du quartier. Devenez un héros communautaire local !",
      "Sign in to start earning points, tracking achievements, and verifying issues!": "Connectez-vous pour commencer à gagner des points, suivre vos réalisations et vérifier les problèmes !",
      "Description": "Description",
      "Location Name": "Nom de l'Emplacement",
      "Civic Impact Analytics": "Analyses d'Impact Civique",
      "Report New Civic Issue": "Signaler un Nouveau Problème Civique",
      "Title": "Titre",
      "Category": "Catégorie",
      "Urgency": "Urgence",
      "Submit Report": "Soumettre le Rapport",
      "Cancel": "Annuler",
      "Audio Notes": "Notes Audio",
      "Speech to Text Input": "Entrée Voix vers Texte",
      "Listen (Voice Note)": "Écouter (Note Vocale)",
      "Recording...": "Enregistrement...",
      "Translate Issue Details": "Traduire les Détails",
      "Track Your Points & Badges": "Suivre Vos Points & Badges",
      "Create an account or sign in as Guest to earn XP for filing reports, verifying issues, and repairing local city infrastructure!": "Créez un compte ou connectez-vous en tant qu'Invité pour gagner des XP en signalant des problèmes, vérifiant des incidents et réparant l'infrastructure locale !",
      "Sign In / Open Hero Panel": "Se Connecter / Ouvrir le Panneau de Héros",
      "Active Level": "Niveau Actif",
      "Rank: Level": "Rang : Niveau",
      "PROGRESS TO LEVEL": "PROGRESSION VERS LE NIVEAU",
      "Earn": "Gagnez",
      "more XP": "plus d'XP",
      "to level up and unlock exclusive city profile styles!": "pour monter de niveau et déverrouiller des styles de profil de ville exclusifs !",
      "My Civic Achievements": "Mes Réalisations Civiques",
      "First Step": "Premier Pas",
      "Rookie Reporter": "Reporter Novice",
      "Civic Champion": "Champion Civique",
      "Eagle Eye": "Œil de Faucon",
      "Elite Validator": "Validateur d'Élite",
      "Problem Solver": "Résolveur de Problèmes",
      "Neighborhood Guardian": "Gardien de Quartier",
      "Super Citizen": "Super Citoyen",
      "Welcome Bonus: Initial registration into the Austin Civic Network.": "Bonus de Bienvenue : Inscription initiale au réseau civique d'Austin.",
      "Logged your first civic issue! The city appreciates your keen eyes.": "Premier problème civique enregistré ! La ville apprécie votre vigilance.",
      "Reported 5 or more distinct active civic maintenance issues.": "A signalé 5 problèmes d'entretien civique actifs distincts ou plus.",
      "Validated another user's report. Helping maintain grid integrity.": "A validé le rapport d'un autre utilisateur. Contribue à maintenir l'intégrité de la grille.",
      "Verified 5 or more distinct reports to assist civic municipal crews.": "A vérifié 5 rapports distincts ou plus pour aider les équipes municipales.",
      "Successfully had one of your reported issues marked as 'Resolved'.": "Un de vos problèmes signalés a été marqué comme 'Résolu' avec succès.",
      "Eclipsed 200 total civic contribution experience points.": "A dépassé 200 points d'expérience de contribution civique au total.",
      "Exceeded 500 total points. Legendary status in our Austin metro grid.": "A dépassé 500 points au total. Statut légendaire sur la grille métropolitaine d'Austin.",
      "Special achievement earned for helping the city.": "Réalisation spéciale obtenue pour avoir aidé la ville.",
      "Reports": "Signalements",
      "Logged Reports": "Rapports Enregistrés",
      "Issues Resolved": "Problèmes Résolus",
      "Active Heroes": "Héros Actifs",
      "Top Contributors": "Meilleurs Contributeurs",
      "No active citizens yet. Be the first to report an issue!": "Pas encore de citoyen actif. Soyez le premier à signaler un problème !",
      "Issues Status Breakdown": "Répartition de l'État des Problèmes",
      "Reports by Category": "Signalements par Catégorie",
      "Activity Trend (Last 7 Days)": "Évolution de l'Activité (7 Derniers Jours)",
      "Gemini Multimodal Reporter": "Reporter Multimodal Gemini",
      "You can upload a photo of the issue, record an audio description, or type what you see. The Gemini API will automatically categorize, name, and assess the urgency of the report.": "Vous pouvez télécharger une photo du problème, enregistrer une description audio ou taper ce que vous voyez. L'API Gemini classera, nommera et évaluera automatiquement l'urgence du signalement.",
      "What is the issue? (Optional if uploading photo or voice)": "Quel est le problème ? (Optionnel si vous importez une photo ou un enregistrement)",
      "Listening...": "Écoute en cours...",
      "Dictate": "Dicter",
      "Add Photo Evidence": "Ajouter une Preuve Photo",
      "Drag and drop or click to upload": "Glisser-déposer ou cliquer pour télécharger",
      "Record Voice Note": "Enregistrer une Note Vocale",
      "Recording live mic...": "Enregistrement micro en cours...",
      "Stop Recording": "Arrêter l'Enregistrement",
      "Start Mic Recording": "Démarrer l'Enregistrement",
      "Speak and describe the issue out loud instead of writing it!": "Parlez et décrivez le problème à haute voix au lieu de l'écrire !",
      "Write Manually Instead": "Écrire Manuellement à la Place",
      "Gemini Analyzing...": "Analyse Gemini en cours...",
      "Analyze with Gemini AI": "Analyser avec l'IA Gemini",
      "Simulation Mode Active": "Mode Simulation Actif",
      "Gemini Analysis Succeeded!": "Analyse Gemini Réussie !",
      "Calculated a high-quality analysis simulation. Configure GEMINI_API_KEY in Secrets for live multimodal Gemini AI.": "Simulation d'analyse de haute qualité calculée. Configurez GEMINI_API_KEY dans Secrets pour l'IA Gemini multimodale en direct.",
      "Gemini analyzed your multimodal report and extracted the parameters below! Feel free to review and adjust.": "Gemini a analysé votre rapport multimodal et extrait les paramètres ci-dessous ! N'hésitez pas à vérifier et ajuster.",
      "Issue Title": "Titre du Problème",
      "Urgency Level": "Niveau d'Urgence",
      "Location / Address": "Emplacement / Adresse",
      "Dispatch Recommendations (For Civil Crews)": "Recommandations d'Intervention (Pour les équipes)",
      "Go Back": "Retour",
      "Submit Civic Report": "Soumettre le Signalement",
      "or continue with": "ou continuer avec",
      "Enter as Guest / Try Demo": "Entrer comme Invité / Essayer la Démo",
      "Join citizens repairing and tracking local civic issues": "Rejoignez les citoyens qui réparent et suivent les problèmes locaux",
      "Your Name": "Votre Nom",
      "Email Address": "Adresse E-mail",
      "Password": "Mot de passe",
      "Create Hero Account": "Créer un Compte de Héros",
      "Sign In": "Se Connecter",
      "All Statuses": "Tous les Statuts",
      "Stop Reading": "Arrêter la Lecture",
      "Translating...": "Traduction...",
      "Show Original": "Afficher l'Original",
      "Verified By You": "Vérifié par Vous",
      "Verifying...": "Vérification...",
      "Live Google Maps": "Google Maps en Direct",
      "Custom Interactive Grid": "Grille Interactive Personnalisée",
      "File a Civic Report": "Déposer un Rapport Civique",
      "Coordinate": "Coordonnée"
  },
kn: {
    "Community Hero": "ಸಮುದಾಯ ಹೀರೋ",
    "Civic Action Platform": "ನಾಗರಿಕ ಕ್ರಿಯಾ ವೇದಿಕೆ",
    "Civic Map & Grid": "ನಾಗರಿಕ ನಕ್ಷೆ ಮತ್ತು ಗ್ರಿಡ್",
    "Impact Analytics": "ಪ್ರಭಾವದ ವಿಶ್ಲೇಷಣೆ",
    "Sign In / Join": "ಸೈನ್ ಇನ್ / ಸೇರಿಕೊಳ್ಳಿ",
    "Notice a civic issue?": "ನಾಗರಿಕ ಸಮಸ್ಯೆ ಗಮನಿಸಿದ್ದೀರಾ?",
    "File Quick Civic Report": "ತ್ವರಿತ ನಾಗರಿಕ ವರದಿ ಸಲ್ಲಿಸಿ",
    "Active Civic Reports": "ಸಕ್ರಿಯ ನಾಗರಿಕ ವರದಿಗಳು",
    "Austin Civic Grid": "ಆಸ್ಟಿನ್ ನಾಗರಿಕ ಗ್ರಿಡ್",
    "Click anywhere on the map to log a new issue": "ಹೊಸ ಸಮಸ್ಯೆಯನ್ನು ದಾಖಲಿಸಲು ನಕ್ಷೆಯಲ್ಲಿ ಎಲ್ಲಿಯಾದರೂ ಕ್ಲಿಕ್ ಮಾಡಿ",
    "Map Legend": "ನಕ್ಷೆಯ ಸೂಚಿಕೆ",
    "Reported": "ವರದಿಯಾಗಿದೆ",
    "Verified": "ಪರಿಶೀಲಿಸಲಾಗಿದೆ",
    "In Progress": "ಪ್ರಗತಿಯಲ್ಲಿದೆ",
    "Resolved": "ಪರಿಹರಿಸಲಾಗಿದೆ",
    "Pothole": "ರಸ್ತೆ ಗುಂಡಿ",
    "Water Leak": "ನೀರು ಸೋರಿಕೆ",
    "Broken Streetlight": "ಕೆಟ್ಟುಹೋದ ಬೀದಿ ದೀಪ",
    "Trash & Dumping": "ಕಸ ಮತ್ತು ತ್ಯಾಜ್ಯ ವಿಲೇವಾರಿ",
    "Graffiti": "ಗೋಡೆ ಬರಹ",
    "Other": "ಇತರೆ",
    "Low": "ಕಡಿಮೆ",
    "Medium": "ಮಧ್ಯಮ",
    "High": "ಹೆಚ್ಚು",
    "Critical": "ನಿರ್ಣಾಯಕ",
    "Sign Out": "ಸೈನ್ ಔಟ್",
    "Verifications": "ಪರಿಶೀಲನೆಗಳು",
    "Verify Issue": "ಸಮಸ್ಯೆ ಪರಿಶೀಲಿಸಿ",
    "Update Status": "ಸ್ಥಿತಿಯನ್ನು ನವೀಕರಿಸಿ",
    "Speak": "ಮಾತನಾಡು",
    "Listen": "ಕೇಳು (STT)",
    "Translate": "ಭಾಷಾಂತರಿಸಿ",
    "Photo Attachment": "ಫೋಟೋ ಲಗತ್ತು",
    "Voice note attached": "ಧ್ವನಿ ಟಿಪ್ಪಣಿ ಲಗತ್ತಿಸಲಾಗಿದೆ",
    "No issues matching filters": "ಫಿಲ್ಟರ್‌ಗಳಿಗೆ ಹೊಂದಿಕೆಯಾಗುವ ಯಾವುದೇ ಸಮಸ್ಯೆಗಳಿಲ್ಲ",
    "Try changing your filters or report a new issue directly on the map.": "ನಿಮ್ಮ ಫಿಲ್ಟರ್‌ಗಳನ್ನು ಬದಲಾಯಿಸಲು ಪ್ರಯತ್ನಿಸಿ ಅಥವಾ ನೇರವಾಗಿ ನಕ್ಷೆಯಲ್ಲಿ ಹೊಸ ಸಮಸ್ಯೆಯನ್ನು ವರದಿ ಮಾಡಿ.",
    "Click directly on the interactive grid map on the right to pinpoint a precise location, or file an instant report.": "ನಿಖರವಾದ ಸ್ಥಳವನ್ನು ಗುರುತಿಸಲು ಬಲಗಡೆಯಲ್ಲಿರುವ ಸಂವಾದಾತ್ಮಕ ಗ್ರಿಡ್ ನಕ್ಷೆಯ ಮೇಲೆ ನೇರವಾಗಿ ಕ್ಲಿಕ್ ಮಾಡಿ ಅಥವಾ ತ್ವರಿತ ವರದಿಯನ್ನು ಸಲ್ಲಿಸಿ.",
    "Austin Civic Center": "ಆಸ್ಟಿನ್ ನಾಗರಿಕ ಕೇಂದ್ರ",
    "Recommended Action": "ಶಿಫారಸು ಮಾಡಿದ ಕ್ರಮ",
    "Points": "ಅಂಕಗಳು",
    "Your Level": "ನಿಮ್ಮ ಮಟ್ಟ",
    "Active Reports": "ಸಕ್ರಿಯ ವರದಿಗಳು",
    "Leaderboard": "ಲೀಡರ್‌ಬೋರ್ಡ್",
    "Badges Earned": "ಗಳಿಸಿದ ಬ್ಯಾಡ್ಜ್‌ಗಳು",
    "Earn rewards by reporting and verifying neighborhood issues. Become a localized community hero!": "ನೆರೆಹೊರೆಯ ಸಮಸ್ಯೆಗಳನ್ನು ವರದಿ ಮಾಡುವ ಮತ್ತು ಪರಿಶೀಲಿಸುವ ಮೂಲಕ ಬಹುಮಾನಗಳನ್ನು ಗಳಿಸಿ. ಸ್ಥಳೀಯ ಸಮುದಾಯದ ಹೀರೋ ಆಗಿ!",
    "Sign in to start earning points, tracking achievements, and verifying issues!": "ಅಂಕಗಳನ್ನು ಗಳಿಸಲು, ಸಾಧನೆಗಳನ್ನು ಪತ್ತೆಹಚ್ಚಲು ಮತ್ತು ಸಮಸ್ಯೆಗಳನ್ನು ಪರಿಶೀಲಿಸಲು ಸೈನ್ ಇನ್ ಮಾಡಿ!",
    "Description": "ವಿವರಣೆ",
    "Location Name": "ಸ್ಥಳದ ಹೆಸರು",
    "Civic Impact Analytics": "ನಾಗರಿಕ ಪ್ರಭಾವದ ವಿಶ್ಲೇಷಣೆ",
    "Report New Civic Issue": "ಹೊಸ ನಾಗರಿಕ ಸಮಸ್ಯೆಯನ್ನು ವರದಿ ಮಾಡಿ",
    "Title": "ಶೀರ್ಷಿಕೆ",
    "Category": "ವರ್ಗ",
    "Urgency": "ತುರ್ತು",
    "Submit Report": "ವರದಿಯನ್ನು ಸಲ್ಲಿಸಿ",
    "Cancel": "ರದ್ದುಮಾಡಿ",
    "Audio Notes": "ಆಡಿಯೋ ಟಿಪ್ಪಣಿಗಳು",
    "Speech to Text Input": "ಭಾಷಣದಿಂದ ಪಠ್ಯ ಇನ್‌ಪುಟ್",
    "Listen (Voice Note)": "ಕೇಳಿ (ಧ್ವನಿ ಟಿಪ್ಪಣಿ)",
    "Recording...": "ರೆಕಾರ್ಡಿಂಗ್ ಮಾಡಲಾಗುತ್ತಿದೆ...",
    "Translate Issue Details": "ಸಮಸ್ಯೆಯ ವಿವರಗಳನ್ನು ಭಾಷಾಂತರಿಸಿ",
    "Track Your Points & Badges": "ನಿಮ್ಮ ಅಂಕಗಳು ಮತ್ತು ಬ್ಯಾಡ್ಜ್‌ಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ",
    "Create an account or sign in as Guest to earn XP for filing reports, verifying issues, and repairing local city infrastructure!": "ವರದಿಗಳನ್ನು ಸಲ್ಲಿಸಲು, ಸಮಸ್ಯೆಗಳನ್ನು ಪರಿಶೀಲಿಸಲು ಮತ್ತು ಸ್ಥಳೀಯ ನಗರ ಮೂಲಸೌಕರ್ಯಗಳನ್ನು ದುರಸ್ತಿ ಮಾಡಲು XP ಗಳಿಸಲು ಖಾತೆಯನ್ನು ರಚಿಸಿ ಅಥವಾ ಅತಿಥಿಯಾಗಿ ಸೈನ್ ಇನ್ ಮಾಡಿ!",
    "Sign In / Open Hero Panel": "ಸೈನ್ ಇನ್ / ಹೀರೋ ಪ್ಯಾನೆಲ್ ತೆರೆಯಿರಿ",
    "Active Level": "ಸಕ್ರಿಯ ಮಟ್ಟ",
    "Rank: Level": "ಶ್ರೇಣಿ: ಮಟ್ಟ",
    "PROGRESS TO LEVEL": "ಮಟ್ಟಕ್ಕೆ ಪ್ರಗತಿ",
    "Earn": "ಗಳಿಸಿ",
    "more XP": "ಹೆಚ್ಚಿನ XP",
    "to level up and unlock exclusive city profile styles!": "ಮಟ್ಟವನ್ನು ಹೆಚ್ಚಿಸಲು ಮತ್ತು ವಿಶೇಷ ನಗರ ಪ್ರೊಫೈಲ್ ಶೈಲಿಗಳನ್ನು ಅನ್ಲಾಕ್ ಮಾಡಲು!",
    "My Civic Achievements": "ನನ್ನ ನಾಗರಿಕ ಸಾಧನೆಗಳು",
    "First Step": "ಮೊದಲ ಹೆಜ್ಜೆ",
    "Rookie Reporter": "ರೂಕಿ ವರದಿಗಾರ",
    "Civic Champion": "ನಾಗರಿಕ ಚಾಂಪಿಯನ್",
    "Eagle Eye": "ಗಿಡುಗನ ಕಣ್ಣು",
    "Elite Validator": "ಗಣ್ಯ ಪರಿಶೀಲಕ",
    "Problem Solver": "ಸಮಸ್ಯೆ ನಿವಾರಕ",
    "Neighborhood Guardian": "ನೆರೆಹೊರೆಯ ರಕ್ಷಕ",
    "Super Citizen": "ಸೂಪರ್ ಸಿಟಿಜನ್",
    "Welcome Bonus: Initial registration into the Austin Civic Network.": "ಸ್ವಾಗತ ಬೋನಸ್: ಆಸ್ಟಿನ್ ನಾಗರಿಕ ನೆಟ್‌ವರ್ಕ್‌ಗೆ ಆರಂಭಿಕ ನೋಂದಣಿ.",
    "Logged your first civic issue! The city appreciates your keen eyes.": "ನಿಮ್ಮ ಮೊದಲ ನಾಗರಿಕ ಸಮಸ್ಯೆಯನ್ನು ಲಾಗ್ ಮಾಡಲಾಗಿದೆ! ನಗರವು ನಿಮ್ಮ ತೀವ್ರ ಕಣ್ಣುಗಳನ್ನು ಪ್ರಶಂಸಿಸುತ್ತದೆ.",
    "Reported 5 or more distinct active civic maintenance issues.": "5 ಅಥವಾ ಅದಕ್ಕಿಂತ ಹೆಚ್ಚು ವಿಭಿನ್ನ ಸಕ್ರಿಯ ನಾಗರಿಕ ನಿರ್ವಹಣಾ ಸಮಸ್ಯೆಗಳನ್ನು ವರದಿ ಮಾಡಲಾಗಿದೆ.",
    "Validated another user's report. Helping maintain grid integrity.": "ಮತ್ತೊಬ್ಬ ಬಳಕೆದಾರರ ವರದಿಯನ್ನು ಮೌಲ್ಯೀಕರಿಸಲಾಗಿದೆ. ಗ್ರಿಡ್ ಸಮಗ್ರತೆಯನ್ನು ಕಾಪಾಡಿಕೊಳ್ಳಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ.",
    "Verified 5 or more distinct reports to assist civic municipal crews.": "ನಾಗರಿಕ ಪುರಸಭೆಯ ಸಿಬ್ಬಂದಿಗೆ ಸಹಾಯ ಮಾಡಲು 5 ಅಥವಾ ಹೆಚ್ಚಿನ ವಿಭಿನ್ನ ವರದಿಗಳನ್ನು ಪರಿಶೀಲಿಸಲಾಗಿದೆ.",
    "Successfully had one of your reported issues marked as 'Resolved'.": "ನಿಮ್ಮ ವರದಿ ಮಾಡಿದ ಸಮಸ್ಯೆಗಳಲ್ಲಿ ಒಂದನ್ನು ಯಶಸ್ವಿಯಾಗಿ 'ಪರಿಹರಿಸಲಾಗಿದೆ' ಎಂದು ಗುರುತಿಸಲಾಗಿದೆ.",
    "Eclipsed 200 total civic contribution experience points.": "ಒಟ್ಟು 200 ನಾಗರಿಕ ಕೊಡುಗೆ ಅನುಭವದ ಅಂಕಗಳನ್ನು ಮೀರಿದೆ.",
    "Exceeded 500 total points. Legendary status in our Austin metro grid.": "ಒಟ್ಟು 500 ಅಂಕಗಳನ್ನು ಮೀರಿದೆ. ನಮ್ಮ ಆಸ್ಟಿನ್ ಮೆಟ್ರೋ ಗ್ರಿಡ್‌ನಲ್ಲಿ ಪೌರಾಣಿಕ ಸ್ಥಾನಮಾನ.",
    "Special achievement earned for helping the city.": "ನಾಗರಿಕ ಸೇವೆಗಾಗಿ ವಿಶೇಷ ಸಾಧನೆ ಗಳಿಸಲಾಗಿದೆ.",
    "Reports": "ವರದಿಗಳು",
    "Logged Reports": "ದಾಖಲಾದ ವರದಿಗಳು",
    "Issues Resolved": "ಪರಿಹರಿಸಲಾದ ಸಮಸ್ಯೆಗಳು",
    "Active Heroes": "ಸಕ್ರಿಯ ಹೀರೋಗಳು",
    "Top Contributors": "ಉನ್ನತ ಕೊಡುಗೆದಾರರು",
    "No active citizens yet. Be the first to report an issue!": "ಇನ್ನೂ ಯಾವುದೇ ಸಕ್ರಿಯ ನಾಗರಿಕರಿಲ್ಲ. ಸಮಸ್ಯೆಯನ್ನು ವರದಿ ಮಾಡುವಲ್ಲಿ ಮೊದಲಿಗರಾಗಿರಿ!",
    "Issues Status Breakdown": "ಸಮಸ್ಯೆಗಳ ಸ್ಥಿತಿಯ ಸ್ಥಗಿತ",
    "Reports by Category": "ವರ್ಗದ ಪ್ರಕಾರ ವರದಿಗಳು",
    "Activity Trend (Last 7 Days)": "ಚಟುವಟಿಕೆ ಪ್ರವೃತ್ತಿ (ಕೊನೆಯ 7 ದಿನಗಳು)",
    "Gemini Multimodal Reporter": "ಜೆಮಿನಿ ಮಲ್ಟಿಮೋಡಲ್ ವರದಿಗಾರ",
    "You can upload a photo of the issue, record an audio description, or type what you see. The Gemini API will automatically categorize, name, and assess the urgency of the report.": "ನೀವು ಸಮಸ್ಯೆಯ ಫೋಟೋವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಬಹುದು, ಆಡಿಯೊ ವಿವರಣೆಯನ್ನು ರೆಕಾರ್ಡ್ ಮಾಡಬಹುದು ಅಥವಾ ನೀವು ನೋಡುವುದನ್ನು ಟೈಪ್ ಮಾಡಬಹುದು. ಜೆಮಿನಿ API ಸ್ವಯಂಚಾಲಿತವಾಗಿ ವರ್ಗೀಕರಿಸುತ್ತದೆ, ಹೆಸರಿಸುತ್ತದೆ ಮತ್ತು ವರದಿಯ ತುರ್ತುಸ್ಥಿತಿಯನ್ನು ನಿರ್ಣಯಿಸುತ್ತದೆ.",
    "What is the issue? (Optional if uploading photo or voice)": "ಸಮಸ್ಯೆ ಏನು? (ಫೋಟೋ ಅಥವಾ ಧ್ವನಿಯನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡುತ್ತಿದ್ದರೆ ಐಚ್ಛಿಕ)",
    "Listening...": "ಕೇಳಿಸಿಕೊಳ್ಳಲಾಗುತ್ತಿದೆ...",
    "Dictate": "ಡಿಕ್ಟೇಟ್ ಮಾಡಿ",
    "Add Photo Evidence": "ಫೋಟೋ ಪುರಾವೆ ಸೇರಿಸಿ",
    "Drag and drop or click to upload": "ಅಪ್‌ಲೋಡ್ ಮಾಡಲು ಎಳೆಯಿರಿ ಮತ್ತು ಬಿಡಿ ಅಥವಾ ಕ್ಲಿಕ್ ಮಾಡಿ",
    "Record Voice Note": "ಧ್ವನಿ ಟಿಪ್ಪಣಿಯನ್ನು ರೆಕಾರ್ಡ್ ಮಾಡಿ",
    "Recording live mic...": "ಲೈವ್ ಮೈಕ್ ರೆಕಾರ್ಡಿಂಗ್ ಮಾಡಲಾಗುತ್ತಿದೆ...",
    "Stop Recording": "ರೆಕಾರ್ಡಿಂಗ್ ನಿಲ್ಲಿಸಿ",
    "Start Mic Recording": "ಮೈಕ್ ರೆಕಾರ್ಡಿಂಗ್ ಪ್ರಾರಂಭಿಸಿ",
    "Speak and describe the issue out loud instead of writing it!": "ಸಮಸ್ಯೆಯನ್ನು ಬರೆಯುವ ಬದಲು ಗಟ್ಟಿಯಾಗಿ ಮಾತನಾಡಿ ಮತ್ತು ವಿವರಿಸಿ!",
    "Write Manually Instead": "ಬದಲಿಗೆ ಹಸ್ತಚಾಲಿತವಾಗಿ ಬರೆಯಿರಿ",
    "Gemini Analyzing...": "ಜೆಮಿನಿ ವಿಶ್ಲೇಷಿಸುತ್ತಿದೆ...",
    "Analyze with Gemini AI": "ಜೆಮಿನಿ AI ನೊಂದಿಗೆ ವಿಶ್ಲೇಷಿಸಿ",
    "Simulation Mode Active": "ಸಿಮ್ಯುಲೇಶನ್ ಮೋಡ್ ಸಕ್ರಿಯವಾಗಿದೆ",
    "Gemini Analysis Succeeded!": "ಜೆಮಿನಿ ವಿಶ್ಲೇಷಣೆ ಯಶಸ್ವಿಯಾಗಿದೆ!",
    "Calculated a high-quality analysis simulation. Configure GEMINI_API_KEY in Secrets for live multimodal Gemini AI.": "ಉತ್ತಮ ಗುಣಮಟ್ಟದ ವಿಶ್ಲೇಷಣಾ ಸಿಮ್ಯುಲೇಶನ್ ಅನ್ನು ಲೆಕ್ಕಹಾಕಲಾಗಿದೆ. ಲೈವ್ ಮಲ್ಟಿಮೋಡಲ್ ಜೆಮಿನಿ AI ಗಾಗಿ ರಹಸ್ಯಗಳಲ್ಲಿ GEMINI_API_KEY ಅನ್ನು ಕಾನ್ಫಿಗರ್ ಮಾಡಿ.",
    "Gemini analyzed your multimodal report and extracted the parameters below! Feel free to review and adjust.": "ಜೆಮಿನಿ ನಿಮ್ಮ ಮಲ್ಟಿಮೋಡಲ್ ವರದಿಯನ್ನು ವಿಶ್ಲೇಷಿಸಿದೆ ಮತ್ತು ಕೆಳಗಿನ ನಿಯತಾಂಕಗಳನ್ನು ಹೊರತೆಗೆದಿದೆ! ಪರಿಶೀಲಿಸಲು ಮತ್ತು ಹೊಂದಿಸಲು ಮುಕ್ತವಾಗಿರಿ.",
    "Issue Title": "ಸಮಸ್ಯೆಯ ಶೀರ್ಷಿಕೆ",
    "Urgency Level": "ತುರ್ತು ಮಟ್ಟ",
    "Location / Address": "ಸ್ಥಳ / ವಿಳಾಸ",
    "Dispatch Recommendations (For Civil Crews)": "ರವಾನೆ ಶಿಫಾರಸುಗಳು (ನಾಗರಿಕ ಸಿಬ್ಬಂದಿಗೆ)",
    "Go Back": "ಹಿಂದಕ್ಕೆ ಹೋಗಿ",
    "Submit Civic Report": "ನಾಗರಿಕ ವರದಿಯನ್ನು ಸಲ್ಲಿಸಿ",
    "or continue with": "ಅಥವಾ ಇದರೊಂದಿಗೆ ಮುಂದುವರಿಯಿರಿ",
    "Enter as Guest / Try Demo": "ಅತಿಥಿಯಾಗಿ ನಮೂದಿಸಿ / ಡೆಮೊ ಪ್ರಯತ್ನಿಸಿ",
    "Join citizens repairing and tracking local civic issues": "ಸ್ಥಳೀಯ ನಾಗರಿಕ ಸಮಸ್ಯೆಗಳನ್ನು ಸರಿಪಡಿಸುವ ಮತ್ತು ಟ್ರ್ಯಾಕ್ ಮಾಡುವ ನಾಗರಿಕರನ್ನು ಸೇರಿಕೊಳ್ಳಿ"
  },
ta: {
    "Community Hero": "சமூக ஹீரோ",
    "Civic Action Platform": "குடிமை நடவடிக்கை தளம்",
    "Civic Map & Grid": "குடிமை வரைபடம் மற்றும் கட்டம்",
    "Impact Analytics": "தாக்க பகுப்பாய்வு",
    "Sign In / Join": "உள்நுழைக / இணையுங்கள்",
    "Notice a civic issue?": "குடிமைப் பிரச்சனையை கவனித்தீர்களா?",
    "File Quick Civic Report": "விரைவான புகார் அளிக்கவும்",
    "Active Civic Reports": "செயலில் உள்ள புகார்கள்",
    "Austin Civic Grid": "ஆஸ்டின் குடிமை கட்டம்",
    "Click anywhere on the map to log a new issue": "புதிய சிக்கலைப் பதிவு செய்ய வரைபடத்தில் எங்கு வேண்டுமானாலும் கிளிக் செய்யவும்",
    "Map Legend": "வரைபட குறியீடு",
    "Reported": "புகாரளிக்கப்பட்டது",
    "Verified": "சரிபார்க்கப்பட்டது",
    "In Progress": "செயல்பாட்டில் உள்ளது",
    "Resolved": "தீர்க்கப்பட்டது",
    "Pothole": "சாலை பள்ளம்",
    "Water Leak": "நீர் கசிவு",
    "Broken Streetlight": "பழுதடைந்த தெருவிளக்கு",
    "Trash & Dumping": "குப்பை கொட்டுதல்",
    "Graffiti": "சுவரோவியம்",
    "Other": "இதர",
    "Low": "குறைந்த",
    "Medium": "நடுத்தர",
    "High": "அதிக",
    "Critical": "மிகவும் முக்கியம்",
    "Sign Out": "வெளியேறு",
    "Verifications": "சரிபார்ப்புகள்",
    "Verify Issue": "சிக்கலைச் சரிபார்",
    "Update Status": "நிலையைப் புதுப்பி",
    "Speak": "பேசு",
    "Listen": "கேள் (STT)",
    "Translate": "மொழிபெயர்",
    "Photo Attachment": "புகைப்பட இணைப்பு",
    "Voice note attached": "குரல் குறிப்பு இணைக்கப்பட்டுள்ளது",
    "No issues matching filters": "வடிப்பான்களுடன் பொருந்தும் சிக்கல்கள் எதுவும் இல்லை",
    "Try changing your filters or report a new issue directly on the map.": "உங்கள் வடிப்பான்களை மாற்ற முயற்சிக்கவும் அல்லது வரைபடத்தில் நேரடியாக ஒரு புதிய சிக்கலைப் புகாரளிக்கவும்.",
    "Click directly on the interactive grid map on the right to pinpoint a precise location, or file an instant report.": "துல்லியமான இடத்தைக் குறிக்க வலதுபுறத்தில் உள்ள ஊடாடும் கட்ட வரைபடத்தில் நேரடியாகக் கிளிக் செய்யவும் அல்லது உடனடி அறிக்கையைத் தாக்கல் செய்யவும்.",
    "Austin Civic Center": "ஆஸ்டின் குடிமை மையம்",
    "Recommended Action": "பரிந்துரைக்கப்பட்ட நடவடிக்கை",
    "Points": "புள்ளிகள்",
    "Your Level": "உங்கள் நிலை",
    "Active Reports": "செயலில் உள்ள அறிக்கைகள்",
    "Leaderboard": "மதிப்பீட்டு பலகை",
    "Badges Earned": "பெற்ற பேட்ஜ்கள்",
    "Earn rewards by reporting and verifying neighborhood issues. Become a localized community hero!": "அக்கம்பக்கத்து பிரச்சனைகளைப் புகாரளித்து சரிபார்ப்பதன் மூலம் அதற்குரிய வெகுமதிகளைப் பெறுங்கள். உள்ளூர் சமூக ஹீரோவாகுங்கள்!",
    "Sign in to start earning points, tracking achievements, and verifying issues!": "புள்ளிகளைப் பெறவும், சாதனைகளைக் கண்காணிக்கவும் மற்றும் சிக்கல்களைச் சரிபார்க்கவும் உள்நுழையவும்!",
    "Description": "விளக்கம்",
    "Location Name": "இடத்தின் பெயர்",
    "Civic Impact Analytics": "குடிமை தாக்க பகுப்பாய்வு",
    "Report New Civic Issue": "புதிய குடிமைப் பிரச்சினையைப் புகாரளிக்கவும்",
    "Title": "தலைப்பு",
    "Category": "வகை",
    "Urgency": "அவசரம்",
    "Submit Report": "அறிக்கையைச் சமர்ப்பி",
    "Cancel": "ரத்துசெய்",
    "Audio Notes": "குரல் குறிப்புகள்",
    "Speech to Text Input": "பேச்சிலிருந்து உரை உள்ளீடு",
    "Listen (Voice Note)": "கேள் (குரல் குறிப்பு)",
    "Recording...": "பதிவு செய்யப்படுகிறது...",
    "Translate Issue Details": "சிக்கல் விவரங்களை மொழிபெயர்",
    "Track Your Points & Badges": "உங்கள் புள்ளிகள் மற்றும் பேட்ஜ்களைக் கண்காணிக்கவும்",
    "Create an account or sign in as Guest to earn XP for filing reports, verifying issues, and repairing local city infrastructure!": "அறிக்கைகளைத் தாக்கல் செய்வதற்கும், சிக்கல்களைச் சரிபார்ப்பதற்கும் மற்றும் உள்ளூர் நகர உள்கட்டமைப்பை சரிசெய்வதற்கும் XP ஐப் பெற ஒரு கணக்கை உருவாக்கவும் அல்லது விருந்தினராக உள்நுழையவும்!",
    "Sign In / Open Hero Panel": "உள்நுழைக / ஹீரோ பேனலைத் திறக்கவும்",
    "Active Level": "செயலில் உள்ள நிலை",
    "Rank: Level": "தரவரிசை: நிலை",
    "PROGRESS TO LEVEL": "நிலைக்கு முன்னேற்றம்",
    "Earn": "பெறுங்கள்",
    "more XP": "கூடுதல் XP",
    "to level up and unlock exclusive city profile styles!": "அடுத்த நிலைக்குச் செல்லவும் மற்றும் பிரத்தியேக நகர சுயவிவர பாணிகளைத் திறக்கவும்!",
    "My Civic Achievements": "எனது குடிமை சாதனைகள்",
    "First Step": "முதல் படி",
    "Rookie Reporter": "தொடக்க நிருபர்",
    "Civic Champion": "குடிமை வெற்றியாளர்",
    "Eagle Eye": "கழுகுப் பார்வை",
    "Elite Validator": "எலைட் சரிபார்ப்பாளர்",
    "Problem Solver": "சிக்கல் தீர்ப்பவர்",
    "Neighborhood Guardian": "அக்கம்பக்கத்து பாதுகாவலர்",
    "Super Citizen": "சூப்பர் குடிமகன்",
    "Welcome Bonus: Initial registration into the Austin Civic Network.": "வரவேற்பு போனஸ்: ஆஸ்டின் குடிமை நெட்வொர்க்கில் ஆரம்ப பதிவு.",
    "Logged your first civic issue! The city appreciates your keen eyes.": "உங்கள் முதல் குடிமைப் பிரச்சினையை பதிவு செய்துள்ளீர்கள்! உங்கள் கூர்மையான பார்வையை நகரம் பாராட்டுகிறது.",
    "Reported 5 or more distinct active civic maintenance issues.": "5 அல்லது அதற்கு மேற்பட்ட தனித்துவமான செயலில் உள்ள குடிமை பராமரிப்பு சிக்கல்களைப் புகாரளித்துள்ளனர்.",
    "Validated another user's report. Helping maintain grid integrity.": "மற்றொரு பயனரின் அறிக்கையை சரிபார்த்தார். கட்டத்தின் ஒருமைப்பாட்டை பராமரிக்க உதவுகிறது.",
    "Verified 5 or more distinct reports to assist civic municipal crews.": "நகராட்சி ஊழியர்களுக்கு உதவ 5 அல்லது அதற்கு மேற்பட்ட தனித்துவமான அறிக்கைகளை சரிபார்த்தார்.",
    "Successfully had one of your reported issues marked as 'Resolved'.": "நீங்கள் புகாரளித்த சிக்கல்களில் ஒன்று வெற்றிகரமாக 'தீர்க்கப்பட்டது' என குறிக்கப்பட்டது.",
    "Eclipsed 200 total civic contribution experience points.": "மொத்தம் 200 குடிமை பங்களிப்பு अनुभव புள்ளிகளை தாண்டியது.",
    "Exceeded 500 total points. Legendary status in our Austin metro grid.": "மொத்தம் 500 புள்ளிகளைத் தாண்டியது. எங்கள் ஆஸ்டின் मेट्रो கட்டத்தில் புகழ்பெற்ற அந்தஸ்து.",
    "Special achievement earned for helping the city.": "நகரத்திற்கு உதவியதற்காக பெற்ற சிறப்பு சாதனை.",
    "Reports": "அறிக்கைகள்",
    "Logged Reports": "பதிவு செய்யப்பட்ட அறிக்கைகள்",
    "Issues Resolved": "தீர்க்கப்பட்ட சிக்கல்கள்",
    "Active Heroes": "செயலில் உள்ள ஹீரோக்கள்",
    "Top Contributors": "சிறந்த பங்களிப்பாளர்கள்",
    "No active citizens yet. Be the first to report an issue!": "இன்னும் செயலில் உள்ள குடிமக்கள் யாரும் இல்லை. பிரச்சினையைப் புகாரளிப்பதில் முதல் ஆளாக இருங்கள்!",
    "Issues Status Breakdown": "சிக்கல்களின் நிலை முறிவு",
    "Reports by Category": "வகை வாரியாக அறிக்கைகள்",
    "Activity Trend (Last 7 Days)": "செயல்பாட்டு போக்கு (கடந்த 7 நாட்கள்)",
    "Gemini Multimodal Reporter": "ஜெமினி மல்டிமாடல் ரிப்போர்ட்டர்",
    "You can upload a photo of the issue, record an audio description, or type what you see. The Gemini API will automatically categorize, name, and assess the urgency of the report.": "சிக்கலின் புகைப்படத்தைப் பதிவேற்றலாம், ஆடியோ விளக்கத்தைப் பதிவு செய்யலாம் அல்லது நீங்கள் பார்ப்பதைத் தட்டச்சு செய்யலாம். ஜெமினி API தானாகவே வகைப்படுத்தி, பெயரிட்டு, அறிக்கையின் அவசரத்தை மதிப்பிடும்.",
    "What is the issue? (Optional if uploading photo or voice)": "பிரச்சனை काय? (புகைப்படம் அல்லது குரலைப் பதிவேற்றினால் விருப்பத்தேர்வு)",
    "Listening...": "கேட்கிறது...",
    "Dictate": "வாசி",
    "Add Photo Evidence": "புகைப்பட ஆதாரத்தைச் சேர்",
    "Drag and drop or click to upload": "பதிவேற்ற இழுத்து விடவும் அல்லது கிளிக் செய்யவும்",
    "Record Voice Note": "குரல் குறிப்பைப் பதிவு செய்",
    "Recording live mic...": "மைக் மூலம் நேரடியாகப் பதிவு செய்யப்படுகிறது...",
    "Stop Recording": "பதிவை நிறுத்து",
    "Start Mic Recording": "மைக் பதிவைத் தொடங்கு",
    "Speak and describe the issue out loud instead of writing it!": "பிரச்சினையை எழுதுவதற்குப் பதிலாக சத்தமாகப் பேசி விவரிக்கவும்!",
    "Write Manually Instead": "அதற்குப் பதிலாக கைமுறையாக எழுதவும்",
    "Gemini Analyzing...": "ஜெமினி பகுப்பாய்வு செய்கிறது...",
    "Analyze with Gemini AI": "ஜெமினி AI மூலம் பகுப்பாய்வு செய்",
    "Simulation Mode Active": "சிமுலேஷன் பயன்முறை செயல்பாட்டில் உள்ளது",
    "Gemini Analysis Succeeded!": "ஜெமினி பகுப்பாய்வு வெற்றியடைந்தது!",
    "Calculated a high-quality analysis simulation. Configure GEMINI_API_KEY in Secrets for live multimodal Gemini AI.": "உயர்தர பகுப்பாய்வு உருவகப்படுத்துதல் கணக்கிடப்பட்டுள்ளது. லைவ் மல்டிமாடல் ஜெமினி AIக்கு ரகசியங்களில் GEMINI_API_KEY ஐ உள்ளமைக்கவும்.",
    "Gemini analyzed your multimodal report and extracted the parameters below! Feel free to review and adjust.": "ஜெமினி உங்கள் மல்டிமாடல் அறிக்கையைப் பகுப்பாய்வு செய்து கீழே உள்ள அளவுருக்களைப் பிரித்தெடுத்தது! மதிப்பாய்வு செய்து சரிசெய்ய தயங்க வேண்டாம்.",
    "Issue Title": "சிக்கலின் தலைப்பு",
    "Urgency Level": "அவசர நிலை",
    "Location / Address": "இடம் / முகவரி",
    "Dispatch Recommendations (For Civil Crews)": "பணி பரிந்துரைகள் (குடிமைப் பணியாளர்களுக்கு)",
    "Go Back": "பின்னால் செல்",
    "Submit Civic Report": "குடிமை அறிக்கையைச் சமர்ப்பி",
    "or continue with": "அல்லது இதனுடன் தொடரவும்",
    "Enter as Guest / Try Demo": "விருந்தினராக உள்ளிடவும் / டெமோவை முயற்சிக்கவும்",
    "Join citizens repairing and tracking local civic issues": "உள்ளூர் குடிமைப் பிரச்சினைகளை சரிசெய்யும் மற்றும் கண்காணிக்கும் குடிமக்களுடன் இணையுங்கள்"
  },
te: {
    "Community Hero": "కమ్యూనిటీ హీరో",
    "Civic Action Platform": "పౌర కార్యాచరణ వేదిక",
    "Civic Map & Grid": "పౌర పటం మరియు గ్రిడ్",
    "Impact Analytics": "ప్రభావ విశ్లేషణ",
    "Sign In / Join": "లాగిన్ / చేరండి",
    "Notice a civic issue?": "పౌర సమస్యను గమనించారా?",
    "File Quick Civic Report": "త్వరిత పౌర నివేదిక",
    "Active Civic Reports": "క్రియాశీల పౌర నివేదికలు",
    "Austin Civic Grid": "ఆస్టిన్ పౌర గ్రిడ్",
    "Click anywhere on the map to log a new issue": "కొత్త సమస్యను నమోదు చేయడానికి మ్యాప్‌లో ఎక్కడైనా క్లిక్ చేయండి",
    "Map Legend": "మ్యాప్ సూచిక",
    "Reported": "निవేదించబడింది",
    "Verified": "ధృవీకరించబడింది",
    "In Progress": "ప్రక్రియలో ఉంది",
    "Resolved": "పరిష్కరించబడింది",
    "Pothole": "రోడ్డు గుంత",
    "Water Leak": "నీటి లీకేజీ",
    "Broken Streetlight": "పనిచేయని వీధి దీపం",
    "Trash & Dumping": "చెత్త మరియు వేయడం",
    "Graffiti": "గ్రాఫిటీ",
    "Other": "ఇతర",
    "Low": "తక్కువ",
    "Medium": "మధ్యస్థం",
    "High": "ఎక్కువ",
    "Critical": "తీవ్రమైన",
    "Sign Out": "లాగ్ అవుట్",
    "Verifications": "ధృవీకరణలు",
    "Verify Issue": "సమస్యను ధృవీకరించు",
    "Update Status": "స్థితిని నవీకరించు",
    "Speak": "మాట్లాడు",
    "Listen": "వినండి (STT)",
    "Translate": "అనువదించు",
    "Photo Attachment": "ఫోటో అటాచ్‌మెంట్",
    "Voice note attached": "వాయిస్ నోట్ జత చేయబడింది",
    "No issues matching filters": "ఫిల్టర్‌లకు సరిపోయే సమస్యలు లేవు",
    "Try changing your filters or report a new issue directly on the map.": "మీ ఫిల్టర్‌లను మార్చడానికి ప్రయత్నించండి లేదా నేరుగా మ్యాప్‌లో కొత్త సమస్యను నివేదించండి.",
    "Click directly on the interactive grid map on the right to pinpoint a precise location, or file an instant report.": "ఖచ్చితమైన స్థానాన్ని సూచించడానికి కుడి వైపున ఉన్న ఇంటరాక్టివ్ గ్రిడ్ మ్యాప్‌పై నేరుగా క్లిక్ చేయండి లేదా తక్షణ నివేదికను దాఖలు చేయండి.",
    "Austin Civic Center": "ఆస్టిన్ పౌర కేంద్రం",
    "Recommended Action": "సిఫార్సు చేయబడిన చర్య",
    "Points": "పాయింట్లు",
    "Your Level": "మీ స్థాయి",
    "Active Reports": "క్రియాశీల నివేదికలు",
    "Leaderboard": "లీడర్‌బోర్డ్",
    "Badges Earned": "సంపాదించిన బ్యాడ్జీలు",
    "Earn rewards by reporting and verifying neighborhood issues. Become a localized community hero!": "పొరుగు సమస్యలను నివేదించడం మరియు ధృవీకరించడం ద్వారా రివార్డులను సంపాదించండి. స్థానిక కమ్యూనిటీ హీరో అవ్వండి!",
    "Sign in to start earning points, tracking achievements, and verifying issues!": "పాయింట్లు సంపాదించడం, విజయాలు ట్రాక్ చేయడం మరియు సమస్యలను ధృవీకరించడం ప్రారంభించడానికి లాగిన్ అవ్వండి!",
    "Description": "వివరణ",
    "Location Name": "స్థలం పేరు",
    "Civic Impact Analytics": "పౌర ప్రభావ విశ్లేషణ",
    "Report New Civic Issue": "కొత్త పౌర సమస్యను నివేదించు",
    "Title": "శీర్షిక",
    "Category": "వర్గం",
    "Urgency": "అవసరం",
    "Submit Report": "నివేదికను సమర్పించు",
    "Cancel": "రద్దు చేయి",
    "Audio Notes": "ఆడియో నోట్స్",
    "Speech to Text Input": "స్పీచ్ టు టెక్స్ట్ ఇన్‌పుట్",
    "Listen (Voice Note)": "వినండి (వాయిస్ నోట్)",
    "Recording...": "రికార్డింగ్ అవుతోంది...",
    "Translate Issue Details": "సమస్య వివరాలను అనువదించు",
    "Track Your Points & Badges": "మీ పాయింట్లు & బ్యాడ్జీలను ట్రాక్ చేయండి",
    "Create an account or sign in as Guest to earn XP for filing reports, verifying issues, and repairing local city infrastructure!": "నివేదికలను దాఖలు చేయడానికి, సమస్యలను ధృవీకరించడానికి మరియు స్థానిక నగర మౌలిక సదుపాయాలను మరమ్మతు చేయడానికి XPని సంపాదించడానికి ఖాతాను సృష్టించండి లేదా అతిథిగా లాగిన్ అవ్వండి!",
    "Sign In / Open Hero Panel": "లాగిన్ / హీరో ప్యానెల్ తెరవండి",
    "Active Level": "క్రియాశీల స్థాయి",
    "Rank: Level": "ర్యాంక్: స్థాయి",
    "PROGRESS TO LEVEL": "స్థాయికి పురోగతి",
    "Earn": "సంపాదించండి",
    "more XP": "మరింత XP",
    "to level up and unlock exclusive city profile styles!": "స్థాయిని పెంచడానికి మరియు ప్రత్యేకమైన నగర ప్రొఫైల్ శైలులను అన్‌లాక్ చేయడానికి!",
    "My Civic Achievements": "నా పౌర విజయాలు",
    "First Step": "మొదటి అడుగు",
    "Rookie Reporter": "రూకీ రిపోర్టర్",
    "Civic Champion": "పౌర ఛాంపియన్",
    "Eagle Eye": "డేగ కన్ను",
    "Elite Validator": "ఎలైట్ వాలిడేటర్",
    "Problem Solver": "సమస్య పరిష్కర్త",
    "Neighborhood Guardian": "పొరుగు రక్షకుడు",
    "Super Citizen": "సూపర్ సిటిజన్",
    "Welcome Bonus: Initial registration into the Austin Civic Network.": "స్వాగత బోనస్: ఆస్టిన్ సివిక్ నెట్‌వర్క్‌లో ప్రారంభ నమోదు.",
    "Logged your first civic issue! The city appreciates your keen eyes.": "మీ మొదటి పౌర సమస్యను నమోదు చేసారు! నగరం మీ శ్రద్ధగల కళ్ళను అభినందిస్తుంది.",
    "Reported 5 or more distinct active civic maintenance issues.": "5 లేదా అంతకంటే ఎక్కువ విభిన్న క్రియాశీల పౌర నిర్వహణ సమస్యలను నివేదించారు.",
    "Validated another user's report. Helping maintain grid integrity.": "మరొక వినియోగదారు నివేదికను ధృవీకరించారు. గ్రిడ్ సమగ్రతను కాపాడటంలో సహాయపడుతుంది.",
    "Verified 5 or more distinct reports to assist civic municipal crews.": "నగరాభివృద్ధి సిబ్బందికి సహాయం చేయడానికి 5 లేదా అంతకంటే ఎక్కువ విభిన్న నివేదికలను ధృవీకరించారు.",
    "Successfully had one of your reported issues marked as 'Resolved'.": "మీరు నివేదించిన సమస్యలలో ఒకటి విజయవంతంగా 'పరిష్కరించబడింది' అని గుర్తించబడింది.",
    "Eclipsed 200 total civic contribution experience points.": "మొత్తం 200 పౌర సహకార అనుభవ పాయింట్లను దాటింది.",
    "Exceeded 500 total points. Legendary status in our Austin metro grid.": "మొత్తం 500 పాయింట్లను మించిపోయింది. మా ఆస్టిన్ మెట్రో గ్రిడ్‌లో లెజెండరీ హోదా.",
    "Special achievement earned for helping the city.": "నగరానికి సహాయం చేసినందుకు పొందిన ప్రత్యేక విజయం.",
    "Reports": "నివేదికలు",
    "Logged Reports": "నమోదైన నివేదికలు",
    "Issues Resolved": "పరిష్కరించబడిన సమస్యలు",
    "Active Heroes": "క్రియాశీల హీరోలు",
    "Top Contributors": "అగ్ర సహకారులు",
    "No active citizens yet. Be the first to report an issue!": "ఇంకా క్రియాశీల పౌరులు లేరు. సమస్యను నివేదించడంలో మొదటి వ్యక్తి అవ్వండి!",
    "Issues Status Breakdown": "సమస్యల స్థితి విభజన",
    "Reports by Category": "వర్గం వారీగా నివేదికలు",
    "Activity Trend (Last 7 Days)": "కార్యాచరణ ట్రెండ్ (గత 7 రోజులు)",
    "Gemini Multimodal Reporter": "జెమిని మల్టీమోడల్ రిపోర్టర్",
    "You can upload a photo of the issue, record an audio description, or type what you see. The Gemini API will automatically categorize, name, and assess the urgency of the report.": "మీరు సమస్య యొక్క ఫోటోను అప్‌లోడ్ చేయవచ్చు, ఆడియో వివరణను రికార్ด์ చేయవచ్చు లేదా మీరు చూసే దాన్ని టైప్ చేయవచ్చు. జెమినీ API స్వయంచాలకంగా నివేదిక యొక్క అత్యవసరతను వర్గీకరిస్తుంది, పేరు పెడుతుంది మరియు అంచనా వేస్తుంది.",
    "What is the issue? (Optional if uploading photo or voice)": "సమస్య ఏమిటి? (ఫోటో లేదా వాయిస్‌ని అప్‌లోడ్ చేస్తుంటే ఐచ్ఛికం)",
    "Listening...": "వింటున్నారు...",
    "Dictate": "డిక్టేట్ చేయి",
    "Add Photo Evidence": "ఫోటో సాక్ష్యాన్ని జోడించు",
    "Drag and drop or click to upload": "అప్‌లోడ్ చేయడానికి లాగి వదలండి లేదా క్లిక్ చేయండి",
    "Record Voice Note": "వాయిస్ నోట్ రికార్డ్ చేయి",
    "Recording live mic...": "లైవ్ మైక్ రికార్డింగ్ అవుతోంది...",
    "Stop Recording": "రికార్డింగ్ ఆపు",
    "Start Mic Recording": "మైక్ రికార్డింగ్ ప్రారంభించు",
    "Speak and describe the issue out loud instead of writing it!": "సమస్యను వ్రాయడానికి బదులుగా బిగ్గరగా మాట్లాడి వివరించండి!",
    "Write Manually Instead": "దానికి బదులుగా మాన్యువల్‌గా రాయండి",
    "Gemini Analyzing...": "జెమిని విశ్లేషిస్తోంది...",
    "Analyze with Gemini AI": "జెమిని AIతో విశ్లేషించు",
    "Simulation Mode Active": "సిమ్యులేషన్ మోడ్ యాక్టివ్‌లో ఉంది",
    "Gemini Analysis Succeeded!": "జెమిని విశ్లేషణ విజయవంతమైంది!",
    "Calculated a high-quality analysis simulation. Configure GEMINI_API_KEY in Secrets for live multimodal Gemini AI.": "అధిక-నాణ్యత విశ్లేషణ అనుకరణ లెక్కించబడింది. ప్రత్యక్ష మల్టీమోడల్ జెమిని AI కోసం సీక్రెట్స్‌లో GEMINI_API_KEYని కాన్ఫిగర్ చేయండి.",
    "Gemini analyzed your multimodal report and extracted the parameters below! Feel free to review and adjust.": "జెమిని మీ మల్టీమోడల్ నివేదికను విశ్లేషించింది మరియు క్రింది పారామితులను సంగ్రహించింది! సమీక్షించడానికి మరియు సర్దుబాటు చేయడానికి సంకోచించకండి.",
    "Issue Title": "సమస్య శీర్షిక",
    "Urgency Level": "అత్యవసర స్థాయి",
    "Location / Address": "స్థలం / చిరునామా",
    "Dispatch Recommendations (For Civil Crews)": "రవాణా సిఫార్సులు (సివిల్ సిబ్బంది కోసం)",
    "Go Back": "వెనక్కి వెళ్ళు",
    "Submit Civic Report": "పౌర నివేదికను సమర్పించు",
    "or continue with": "లేదా దీనితో కొనసాగండి",
    "Enter as Guest / Try Demo": "అతిథిగా నమోదు చేయండి / డెమోని ప్రయత్నించండి",
    "Join citizens repairing and tracking local civic issues": "స్థానిక పౌర సమస్యలను మరమ్మతు చేసే మరియు ట్రాక్ చేసే పౌరులతో చేరండి"
  },
mr: {
    "Community Hero": "कम्युनिटी हिरो",
    "Civic Action Platform": "नागरी कृती मंच",
    "Civic Map & Grid": "नागरी नकाशा आणि ग्रिड",
    "Impact Analytics": "प्रभाव विश्लेषण",
    "Sign In / Join": "साइन इन / सामील व्हा",
    "Notice a civic issue?": "नागरी समस्या आढळली?",
    "File Quick Civic Report": "त्वरित नागरी अहवाल",
    "Active Civic Reports": "सक्रिय नागरी अहवाल",
    "Austin Civic Grid": "ऑस्टिन नागरी ग्रिड",
    "Click anywhere on the map to log a new issue": "नवीन समस्या नोंदवण्यासाठी नकाशावर कुठेही क्लिक करा",
    "Map Legend": "नकाशा सूची",
    "Reported": "नोंदणीकृत",
    "Verified": "सत्यापित",
    "In Progress": "प्रगतीपथावर",
    "Resolved": "निवारण झाले",
    "Pothole": "खड्डा",
    "Water Leak": "पाणी गळती",
    "Broken Streetlight": "बंद पथदिवा",
    "Trash & Dumping": "कचरा आणि डंपिंग",
    "Graffiti": "भित्तीचित्र",
    "Other": "इतर",
    "Low": "कमी",
    "Medium": "मध्यम",
    "High": "उच्च",
    "Critical": "गंभीर",
    "Sign Out": "साइन आउट",
    "Verifications": "सत्यापने",
    "Verify Issue": "समस्या सत्यापित करा",
    "Update Status": "स्थिती अपडेट करा",
    "Speak": "बोला",
    "Listen": "ऐका (STT)",
    "Translate": "अनुवाद करा",
    "Photo Attachment": "फोटो संलग्नक",
    "Voice note attached": "आवाज नोंद जोडली",
    "No issues matching filters": "फिल्टरशी जुळणारी कोणतीही समस्या नाही",
    "Try changing your filters or report a new issue directly on the map.": "तुमचे फिल्टर बदलून पहा किंवा थेट नकाशावर नवीन समस्येची नोंद करा.",
    "Click directly on the interactive grid map on the right to pinpoint a precise location, or file an instant report.": "अचूक स्थान दर्शवण्यासाठी उजवीकडील परस्परसंवादी ग्रिड नकाशावर थेट क्लिक करा, किंवा त्वरित अहवाल नोंदवा.",
    "Austin Civic Center": "ऑस्टिन नागरी केंद्र",
    "Recommended Action": "शिफारस केलेली कारवाई",
    "Points": "गुण",
    "Your Level": "तुमची पातळी",
    "Active Reports": "सक्रिय अहवाल",
    "Leaderboard": "लीडरबोर्ड",
    "Badges Earned": "मिळवलेले बॅज",
    "Earn rewards by reporting and verifying neighborhood issues. Become a localized community hero!": "परिसरातील समस्यांची नोंद आणि पडताळणी करून बक्षिसे मिळवा. स्थानिक कम्युनिटी हिरो बना!",
    "Sign in to start earning points, tracking achievements, and verifying issues!": "गुण मिळवणे, यश ट्रॅक करणे आणि समस्या सत्यापित करणे सुरू करण्यासाठी साइन इन करा!",
    "Description": "वर्णन",
    "Location Name": "ठिकाणाचे नाव",
    "Civic Impact Analytics": "नागरी प्रभाव विश्लेषण",
    "Report New Civic Issue": "नवीन नागरी समस्येची नोंद करा",
    "Title": "शीर्षक",
    "Category": "श्रेणी",
    "Urgency": "तात्काळता",
    "Submit Report": "अहवाल सबमिट करा",
    "Cancel": "रद्द करा",
    "Audio Notes": "ऑडिओ नोट्स",
    "Speech to Text Input": "आवाज ते मजकूर इनपुट",
    "Listen (Voice Note)": "ऐका (आवाज नोंद)",
    "Recording...": "रेकॉर्डिंग सुरू आहे...",
    "Translate Issue Details": "समस्या तपशीलांचे भाषांतर करा",
    "Track Your Points & Badges": "तुमचे गुण आणि बॅज ट्रॅक करा",
    "Create an account or sign in as Guest to earn XP for filing reports, verifying issues, and repairing local city infrastructure!": "अहवाल सबमिट करण्यासाठी, समस्यांची पडताळणी करण्यासाठी आणि स्थानिक शहराच्या पायाभूत सुविधांची दुरुस्ती करण्यासाठी XP मिळवण्यासाठी खाते तयार करा किंवा अतिथी म्हणून साइन इन करा!",
    "Sign In / Open Hero Panel": "साइन इन / हिरो पॅनेल उघडा",
    "Active Level": "सक्रिय पातळी",
    "Rank: Level": "रँक: पातळी",
    "PROGRESS TO LEVEL": "पातळीकडे प्रगती",
    "Earn": "मिळवा",
    "more XP": "अधिक XP",
    "to level up and unlock exclusive city profile styles!": "पातळी वाढवण्यासाठी आणि विशेष शहर प्रोफाइल शैली अनलॉक करण्यासाठी!",
    "My Civic Achievements": "माझे नागरी यश",
    "First Step": "पहिले पाऊल",
    "Rookie Reporter": "नवशिक्या वार्ताहर",
    "Civic Champion": "नागरी चॅम्पियन",
    "Eagle Eye": "गरुड नजर",
    "Elite Validator": "एलिट पडताळणीकर्ता",
    "Problem Solver": "समस्या निवारक",
    "Neighborhood Guardian": "परिसर रक्षक",
    "Super Citizen": "सुपर नागरिक",
    "Welcome Bonus: Initial registration into the Austin Civic Network.": "स्वागत बोनस: ऑस्टिन सिविक नेटवर्कमध्ये सुरुवातीची नोंदणी.",
    "Logged your first civic issue! The city appreciates your keen eyes.": "तुमची पहिली नागरी समस्या नोंदवली! शहर तुमच्या तीक्ष्ण नजरेचे कौतुक करते.",
    "Reported 5 or more distinct active civic maintenance issues.": "५ किंवा अधिक स्वतंत्र सक्रिय नागरी देखभाल समस्यांची नोंद केली आहे.",
    "Validated another user's report. Helping maintain grid integrity.": "दुसऱ्या वापरकर्च्या अहवालाची पडताळणी केली. ग्रिडची अखंडता राखण्यास मदत करत आहे.",
    "Verified 5 or more distinct reports to assist civic municipal crews.": "नागरी महापालिकेच्या पथकांना मदत करण्यासाठी ५ याहून अधिक स्वतंत्र अहवाल सत्यापित केले.",
    "Successfully had one of your reported issues marked as 'Resolved'.": "तुमच्या नोंदवलेल्या समस्यांपैकी एक यशस्वीरित्या 'निवारण झाले' म्हणून चिन्हांकित झाली.",
    "Eclipsed 200 total civic contribution experience points.": "एकूण २०० नागरी योगदान अनुभव गुण ओलांडले.",
    "Exceeded 500 total points. Legendary status in our Austin metro grid.": "एकूण ५०० गुण ओलांडले. आमच्या ऑस्टिन मेट्रो ग्रिडमध्ये दिग्गज दर्जा.",
    "Special achievement earned for helping the city.": "शहराला मदत केल्याबद्दल मिळालेले विशेष यश.",
    "Reports": "अहवाल",
    "Logged Reports": "नोंदवलेले अहवाल",
    "Issues Resolved": "निवारण झालेल्या समस्या",
    "Active Heroes": "सक्रिय हिरो",
    "Top Contributors": "शीर्ष योगदानकर्ते",
    "No active citizens yet. Be the first to report an issue!": "अद्याप कोणीही सक्रिय नागरिक नाही. समस्येची नोंद करणारे पहिले व्हा!",
    "Issues Status Breakdown": "समस्यांच्या स्थितीचे वर्गीकरण",
    "Reports by Category": "श्रेणीनुसार अहवाल",
    "Activity Trend (Last 7 Days)": "कृती कल (गेले ७ दिवस)",
    "Gemini Multimodal Reporter": "जेमिनी मल्टीमोडल रिपोर्टर",
    "You can upload a photo of the issue, record an audio description, or type what you see. The Gemini API will automatically categorize, name, and assess the urgency of the report.": "तुम्ही समस्येचा फोटो अपलोड करू शकता, ऑडिओ वर्णन रेकॉर्ड करू शकता किंवा तुम्हाला काय दिसते ते टाईप करू शकता. जेमिनी API स्वयंचलितपणे अहवालाचे वर्गीकरण करेल, नाव देईल आणि त्याचे गांभीर्य मूल्यांकन करेल.",
    "What is the issue? (Optional if uploading photo or voice)": "समस्या काय आहे? (फोटो किंवा ऑडिओ अपलोड करत असल्यास ऐच्छिक)",
    "Listening...": "ऐकत आहे...",
    "Dictate": "डिक्टेट करा",
    "Add Photo Evidence": "फोटो पुरावा जोडा",
    "Drag and drop or click to upload": "अपलोड करण्यासाठी ड्रॅग आणि ड्रॉप करा किंवा क्लिक करा",
    "Record Voice Note": "आवाज नोंद रेकॉर्ड करा",
    "Recording live mic...": "थेट माईक रेकॉर्डिंग सुरू आहे...",
    "Stop Recording": "रेकॉर्डिंग थांबवा",
    "Start Mic Recording": "माईक रेकॉर्डिंग सुरू करा",
    "Speak and describe the issue out loud instead of writing it!": "समस्या लिहिण्याऐवजी मोठ्याने बोलून त्याचे वर्णन करा!",
    "Write Manually Instead": "त्याऐवजी स्वतः लिहा",
    "Gemini Analyzing...": "जेमिनी विश्लेषण करत आहे...",
    "Analyze with Gemini AI": "जेमिनी AI सह विश्लेषण करा",
    "Simulation Mode Active": "सिम्युलेशन मोड सक्रिय आहे",
    "Gemini Analysis Succeeded!": "जेमिनी विश्लेषण यशस्वी झाले!",
    "Calculated a high-quality analysis simulation. Configure GEMINI_API_KEY in Secrets for live multimodal Gemini AI.": "उच्च-गुणवत्तेचे विश्लेषण सिम्युलेशन मोजले गेले आहे. थेट मल्टीमोडल जेमिनी AI साठी सिक्रेट्समध्ये GEMINI_API_KEY कॉन्फिगर करा.",
    "Gemini analyzed your multimodal report and extracted the parameters below! Feel free to review and adjust.": "जेमिनीने तुमच्या मल्टीमोडल अहवालाचे विश्लेषण केले आहे आणि खालील पॅरामीटर्स काढले आहेत! पुनरावलोकन आणि समायोजन करण्यास मोकळे राहा.",
    "Issue Title": "समस्येचे शीर्षक",
    "Urgency Level": "तात्काळता पातळी",
    "Location / Address": "ठिकाण / पत्ता",
    "Dispatch Recommendations (For Civil Crews)": "कर्मचाऱ्यांसाठी शिफारसी",
    "Go Back": "मागे जा",
    "Submit Civic Report": "नागरी अहवाल सबमिट करा",
    "or continue with": "किंवा याद्वारे पुढे जा",
    "Enter as Guest / Try Demo": "अतिथी म्हणून प्रवेश करा / डेमो पहा",
    "Join citizens repairing and tracking local civic issues": "स्थानिक नागरी समस्या दुरुस्त करणाऱ्या आणि ट्रॅक करणाऱ्या नागरिकांमध्ये सामील व्हा"
  },
ja: {
    "Community Hero": "コミュニティ・ヒーロー",
    "Civic Action Platform": "市民アクションプラットフォーム",
    "Civic Map & Grid": "市民マップ＆グリッド",
    "Impact Analytics": "影響分析",
    "Sign In / Join": "サインイン / 参加",
    "Notice a civic issue?": "地域の課題にお気づきですか？",
    "File Quick Civic Report": "クイック報告を行う",
    "Active Civic Reports": "対応中の市民報告",
    "Austin Civic Grid": "オースティン市民グリッド",
    "Click anywhere on the map to log a new issue": "地図上の任意の場所をクリックして新しい課題を記録",
    "Map Legend": "凡例",
    "Reported": "報告済み",
    "Verified": "確認済み",
    "In Progress": "対応中",
    "Resolved": "解決済み",
    "Pothole": "道路のくぼみ",
    "Water Leak": "水漏れ",
    "Broken Streetlight": "街灯の破損",
    "Trash & Dumping": "ゴミ放置・不法投棄",
    "Graffiti": "落書き",
    "Other": "その他",
    "Low": "低",
    "Medium": "中",
    "High": "高",
    "Critical": "極めて重大",
    "Sign Out": "サインアウト",
    "Verifications": "確認数",
    "Verify Issue": "この課題を確認する",
    "Update Status": "ステータスを更新する",
    "Speak": "音声読み上げ",
    "Listen": "音声入力 (STT)",
    "Translate": "翻訳する",
    "Photo Attachment": "添付写真",
    "Voice note attached": "音声メモ添付あり",
    "No issues matching filters": "フィルターに一致する課題はありません",
    "Try changing your filters or report a new issue directly on the map.": "フィルターを変更するか、地図上で直接新しい課題を報告してください。",
    "Click directly on the interactive grid map on the right to pinpoint a precise location, or file an instant report.": "右側のインタラクティブなグリッドマップを直接クリックして正確な位置を特定するか、即座に報告を作成してください。",
    "Austin Civic Center": "オースティン市民センター",
    "Recommended Action": "推奨される対応策",
    "Points": "ポイント",
    "Your Level": "あなたのレベル",
    "Active Reports": "アクティブな報告",
    "Leaderboard": "リーダーボード",
    "Badges Earned": "獲得バッジ",
    "Earn rewards by reporting and verifying neighborhood issues. Become a localized community hero!": "地域の課題を報告・確認して報酬を獲得しましょう。地元のコミュニティヒーローになりましょう！",
    "Sign in to start earning points, tracking achievements, and verifying issues!": "サインインしてポイントを獲得し、実績を追跡し、課題を確認しましょう！",
    "Description": "説明",
    "Location Name": "場所名",
    "Civic Impact Analytics": "市民活動影響分析",
    "Report New Civic Issue": "新しい市民課題を報告する",
    "Title": "タイトル",
    "Category": "カテゴリー",
    "Urgency": "緊急度",
    "Submit Report": "報告を送信する",
    "Cancel": "キャンセル",
    "Audio Notes": "オーディオメモ",
    "Speech to Text Input": "音声テキスト入力",
    "Listen (Voice Note)": "再生（音声メモ）",
    "Recording...": "録音中...",
    "Translate Issue Details": "課題の詳細を翻訳する",
    "Track Your Points & Badges": "ポイントとバッジを追跡する",
    "Create an account or sign in as Guest to earn XP for filing reports, verifying issues, and repairing local city infrastructure!": "アカウントを作成するかゲストとしてサインインして、報告の提出、課題の確認、地元の都市インフラの修理に対するXPを獲得しましょう！",
    "Sign In / Open Hero Panel": "サインイン / ヒーローパネルを開く",
    "Active Level": "アクティブレベル",
    "Rank: Level": "ランク: レベル",
    "PROGRESS TO LEVEL": "次のレベルへの進捗",
    "Earn": "獲得",
    "more XP": "必要なXP",
    "to level up and unlock exclusive city profile styles!": "レベルアップして、特別な都市プロフィールスタイルをアンロックしましょう！",
    "My Civic Achievements": "私の市民活動実績",
    "First Step": "最初の一歩",
    "Rookie Reporter": "新人記者",
    "Civic Champion": "市民活動のチャンピオン",
    "Eagle Eye": "鋭い観察眼（イーグルアイ）",
    "Elite Validator": "エリート確認官",
    "Problem Solver": "問題解決者",
    "Neighborhood Guardian": "地域の守護者",
    "Super Citizen": "スーパー市民",
    "Welcome Bonus: Initial registration into the Austin Civic Network.": "ウェルカムボーナス：オースティン市民ネットワークへの初回登録。",
    "Logged your first civic issue! The city appreciates your keen eyes.": "最初の市民課題を記録しました！市はあなたの鋭い観察眼に感謝しています。",
    "Reported 5 or more distinct active civic maintenance issues.": "5つ以上のアクティブな市民メンテナンス課題を報告しました。",
    "Validated another user's report. Helping maintain grid integrity.": "他のユーザーの報告を確認しました。グリッドの整合性の維持に貢献しています。",
    "Verified 5 or more distinct reports to assist civic municipal crews.": "地方自治体の作業員を支援するため、5つ以上の異なる報告を確認しました。",
    "Successfully had one of your reported issues marked as 'Resolved'.": "報告した課題の1つが「解決済み」に設定されました。",
    "Eclipsed 200 total civic contribution experience points.": "市民貢献経験値の合計が200ポイントに達しました。",
    "Exceeded 500 total points. Legendary status in our Austin metro grid.": "合計500ポイントを超えました。オースティンメトログリッドにおける伝説的なステータスです。",
    "Special achievement earned for helping the city.": "市を支援したことで獲得した特別な実績。",
    "Reports": "報告数",
    "Logged Reports": "記録された報告数",
    "Issues Resolved": "解決された課題数",
    "Active Heroes": "アクティブなヒーロー数",
    "Top Contributors": "トップ貢献者",
    "No active citizens yet. Be the first to report an issue!": "まだアクティブな市民はいません。最初の報告者になりましょう！",
    "Issues Status Breakdown": "課題ステータス内訳",
    "Reports by Category": "カテゴリー別報告数",
    "Activity Trend (Last 7 Days)": "アクティビティ傾向（過去7日間）",
    "Gemini Multimodal Reporter": "Geminiマルチモーダル・レポーター",
    "You can upload a photo of the issue, record an audio description, or type what you see. The Gemini API will automatically categorize, name, and assess the urgency of the report.": "課題の写真をアップロードしたり、音声による説明を録音したり、見えている内容を入力したりできます。Gemini APIが自動的にカテゴリー分け、命名、報告の緊急度の評価を行います。",
    "What is the issue? (Optional if uploading photo or voice)": "課題の内容は何ですか？（写真や音声のアップロード時は任意）",
    "Listening...": "聞き取り中...",
    "Dictate": "音声ディクテーション",
    "Add Photo Evidence": "写真証拠の追加",
    "Drag and drop or click to upload": "ドラッグ＆ドロップまたはクリックでアップロード",
    "Record Voice Note": "音声メモの録音",
    "Recording live mic...": "マイクからライブ録音中...",
    "Stop Recording": "録音停止",
    "Start Mic Recording": "マイク録音開始",
    "Speak and describe the issue out loud instead of writing it!": "書く代わりに、課題を声に出して説明してください！",
    "Write Manually Instead": "代わりに手動で入力する",
    "Gemini Analyzing...": "Geminiが分析中...",
    "Analyze with Gemini AI": "Gemini AIで分析する",
    "Simulation Mode Active": "シミュレーションモード有効",
    "Gemini Analysis Succeeded!": "Geminiの分析が成功しました！",
    "Calculated a high-quality analysis simulation. Configure GEMINI_API_KEY in Secrets for live multimodal Gemini AI.": "高品質な分析シミュレーションが計算されました。ライブのマルチモーダルGemini AIを使用するには、SecretsでGEMINI_API_KEYを設定してください。",
    "Gemini analyzed your multimodal report and extracted the parameters below! Feel free to review and adjust.": "Geminiがマルチモーダル報告を分析し、以下のパラメータを抽出しました！必要に応じて確認・調整してください。",
    "Issue Title": "課題のタイトル",
    "Urgency Level": "緊急度レベル",
    "Location / Address": "場所 / 住所",
    "Dispatch Recommendations (For Civil Crews)": "作業員への推奨対応指示",
    "Go Back": "戻る",
    "Submit Civic Report": "市民報告を送信する",
    "or continue with": "または以下で継続",
    "Enter as Guest / Try Demo": "ゲストとして入る / デモを試す",
    "Join citizens repairing and tracking local civic issues": "地元の市民課題の修理や追跡を行う市民ネットワークに参加する"
  }
};

interface AppContextType {
  theme: "light" | "dark";
  toggleTheme: () => void;
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string) => string;
  translateDynamicText: (text: string, targetLang: string) => Promise<string>;
  getSpeechAudio: (text: string, lang: string) => Promise<string | null>;
  startSpeechRecognition: (
    onResult: (text: string) => void,
    onError?: (err: any) => void
  ) => { stop: () => void; active: boolean };
}

const AppContext = createContext<AppContextType | undefined>(undefined);

export const AppProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [theme, setTheme] = useState<"light" | "dark">("light");
  const [language, setLanguageState] = useState<LanguageCode>("en");

  // Load theme and language settings on startup
  useEffect(() => {
    const savedTheme = localStorage.getItem("theme") as "light" | "dark" | null;
    const savedLanguage = localStorage.getItem("language") as LanguageCode | null;

    if (savedTheme) {
      setTheme(savedTheme);
      document.documentElement.classList.toggle("dark", savedTheme === "dark");
    } else {
      // Default to light mode on first visit
      setTheme("light");
      document.documentElement.classList.remove("dark");
    }

    if (savedLanguage && ["en", "es", "vi", "hi", "zh", "fr", "kn", "ta", "te", "mr", "ja"].includes(savedLanguage)) {
      setLanguageState(savedLanguage);
    }
  }, []);

  const toggleTheme = () => {
    const nextTheme = theme === "light" ? "dark" : "light";
    setTheme(nextTheme);
    localStorage.setItem("theme", nextTheme);
    document.documentElement.classList.toggle("dark", nextTheme === "dark");
  };

  const setLanguage = (lang: LanguageCode) => {
    setLanguageState(lang);
    localStorage.setItem("language", lang);
  };

  // Translation Function (Local Dictionary Look-up)
  const t = (key: string): string => {
    const dict = TRANSLATIONS[language];
    if (dict && dict[key]) {
      return dict[key];
    }
    // Fallback to English dictionary if key missing in current language
    const enDict = TRANSLATIONS["en"];
    if (enDict && enDict[key]) {
      return enDict[key];
    }
    return key;
  };

  // Dynamic Google/Gemini Translate API request proxy
  const translateDynamicText = async (text: string, targetLang: string): Promise<string> => {
    if (!text || !text.trim()) return "";
    try {
      const res = await fetch("/api/translate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ text, targetLanguage: targetLang })
      });
      if (!res.ok) {
        throw new Error("Translation failed");
      }
      const data = await res.json();
      return data.translatedText || text;
    } catch (err) {
      console.error("Failed to translate dynamically via server, using client local fallback.", err);
      return text;
    }
  };

  // Dynamic Text-To-Speech API request proxy using gemini-3.1-flash-tts-preview
  const getSpeechAudio = async (text: string, lang: string): Promise<string | null> => {
    if (!text || !text.trim()) return null;
    try {
      const res = await fetch("/api/tts", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ text, language: lang })
      });
      if (res.ok) {
        const data = await res.json();
        if (data.audioBase64) {
          return data.audioBase64;
        }
      }
      throw new Error("Backend TTS unavailable");
    } catch (err) {
      console.warn("Server TTS failed or unavailable, falling back to Web Speech API speechSynthesis on client.", err);
      // Fallback: Client-side Native speechSynthesis
      return null;
    }
  };

  // Client-Side Speech Recognition (Speech-to-Text) wrapper using browser native webkitSpeechRecognition API
  const startSpeechRecognition = (
    onResult: (text: string) => void,
    onError?: (err: any) => void
  ) => {
    const SpeechRecognition = (window as any).SpeechRecognition || (window as any).webkitSpeechRecognition;
    if (!SpeechRecognition) {
      console.error("Speech recognition is not supported in this browser.");
      if (onError) onError(new Error("STT not supported in browser"));
      return { stop: () => {}, active: false };
    }

    const recognition = new SpeechRecognition();
    recognition.continuous = false;
    recognition.interimResults = false;

    // Match language code to native locales
    const locales: Record<LanguageCode, string> = {
      en: "en-US",
      es: "es-ES",
      vi: "vi-VN",
      hi: "hi-IN",
      zh: "zh-CN",
      fr: "fr-FR",
      kn: "kn-IN",
      ta: "ta-IN",
      te: "te-IN",
      mr: "mr-IN",
      ja: "ja-JP"
    };
    recognition.lang = locales[language] || "en-US";

    recognition.onresult = (event: any) => {
      const speechToText = event.results[0][0].transcript;
      onResult(speechToText);
    };

    recognition.onerror = (event: any) => {
      console.error("Speech recognition error:", event.error);
      if (onError) onError(event);
    };

    try {
      recognition.start();
      return {
        stop: () => recognition.stop(),
        active: true
      };
    } catch (e) {
      console.error("Recognition start exception", e);
      return { stop: () => {}, active: false };
    }
  };

  return (
    <AppContext.Provider
      value={{
        theme,
        toggleTheme,
        language,
        setLanguage,
        t,
        translateDynamicText,
        getSpeechAudio,
        startSpeechRecognition
      }}
    >
      {children}
    </AppContext.Provider>
  );
};

export const useApp = () => {
  const context = useContext(AppContext);
  if (!context) {
    throw new Error("useApp must be used within an AppProvider");
  }
  return context;
};
